-- Ensure journey_templates has required columns (idempotent for differing existing schemas)
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS sector TEXT NOT NULL DEFAULT '';
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS steps JSONB NOT NULL DEFAULT '[]';
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE journey_templates ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
-- If table has "name" (InvestiGator schema), allow NULL/default so our INSERT (title only) works
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'journey_templates' AND column_name = 'name') THEN
    ALTER TABLE journey_templates ALTER COLUMN name DROP NOT NULL;
    ALTER TABLE journey_templates ALTER COLUMN name SET DEFAULT '';
  END IF;
END $$;

-- 11E-1: Broadband Speed guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'broadband-speed',
  'broadband_speed',
  'Broadband Speed Dispute',
  'Step-by-step guide to resolving a broadband speed complaint, from gathering speed test evidence through to ADR referral via CISAS or Ombudsman Services.',
  'telecoms',
  true,
  $steps$
[
  {"step_id": "gather-speed-evidence", "order": 1, "title": "Gather your speed test evidence", "description": "Before contacting your provider, you need solid evidence that your broadband speed is consistently below what was promised. Run speed tests at different times of day over several days to build a clear picture.", "action_type": "checklist", "action_config": {"items": ["Check your contract for your guaranteed minimum download speed (look for the phrase \"minimum guaranteed speed\" — this is the key figure, not the \"up to\" or \"estimated\" speed)", "Run speed tests using a wired connection (not Wi-Fi) at broadband.ofcom.org.uk or speedtest.net — at least 3 tests at different times of day over 3 separate days", "Screenshot or save each speed test result with the date and time visible", "Upload your speed test results as evidence on this case", "Note your router model and confirm it is the one provided or recommended by your ISP"], "tip": "Wi-Fi speeds are always lower than wired speeds and your ISP will use this to dismiss your complaint. Always test with an ethernet cable plugged directly into your router."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint"},
  {"step_id": "initial-complaint", "order": 2, "title": "Send your formal complaint", "description": "We have drafted a complaint letter to {company_name} that references your speed test evidence and your contractual minimum guaranteed speed. This letter formally opens the complaint and starts the 8-week clock for ADR eligibility.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "broadband_speed_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Give {company_name} 14 days to respond. They may offer to send an engineer or run remote diagnostics. Log any response or contact you receive.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 3, "title": "What happened?", "description": "It has been 14 days since your complaint. Did {company_name} respond, and if so, has the issue been resolved?", "action_type": "branch", "action_config": {"question": "How did your broadband provider respond?", "options": [{"label": "They fixed the speed — resolved", "next_step": "resolved"}, {"label": "They sent an engineer but the speed is still poor", "next_step": "post-engineer"}, {"label": "They offered a partial solution (e.g. discount, lower tariff)", "next_step": "right-to-exit"}, {"label": "No meaningful response", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "post-engineer", "order": 4, "title": "Re-test after the engineer visit", "description": "An engineer visited but your speed may still be below the guaranteed minimum. Run fresh speed tests over the next 3 days using the same wired connection method. If speeds are still below the guaranteed minimum, you can proceed with a follow-up complaint.", "action_type": "checklist", "action_config": {"items": ["Run 3 new speed tests over 3 days (wired connection, different times of day)", "Upload the new speed test results as evidence", "Log what the engineer did and any explanation they gave"]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 3, "wait_message": "Test your speeds over the next few days. If the problem persists, we will help you escalate.", "next_step": "follow-up"},
  {"step_id": "right-to-exit", "order": 5, "title": "Consider your right to exit", "description": "If your provider has signed Ofcom's Voluntary Code of Practice on Broadband Speeds and cannot deliver the minimum guaranteed speed, you have the right to exit your contract without paying an early termination fee. You can use this as leverage: either fix the speed or let you leave penalty-free.", "action_type": "info", "action_config": {"tip": "Most major UK ISPs (BT, Sky, TalkTalk, Plusnet, EE, Vodafone, Virgin Media) have signed the code. If your provider has not signed it, you still have rights under the Consumer Rights Act 2015 — the service must be provided with reasonable care and skill."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "follow-up", "order": 6, "title": "Send a follow-up letter", "description": "Your complaint has not been resolved. This follow-up letter references your ongoing speed evidence, notes the inadequate response, invokes your right to exit under Ofcom's code (if applicable), and warns of ADR escalation.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "broadband_speed_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "Another 14 days for {company_name} to act. If they still cannot fix the issue, we will prepare your ADR referral.", "next_step": "assess-response-2"},
  {"step_id": "assess-response-2", "order": 7, "title": "Final check before ADR", "description": "Has {company_name} resolved the speed issue after your follow-up?", "action_type": "branch", "action_config": {"question": "What is the current situation?", "options": [{"label": "Resolved — speed is now acceptable", "next_step": "resolved"}, {"label": "They let me exit without penalty", "next_step": "resolved"}, {"label": "Still unresolved — I want to escalate", "next_step": "deadlock-or-8-weeks"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "deadlock-or-8-weeks"},
  {"step_id": "deadlock-or-8-weeks", "order": 8, "title": "Request a deadlock letter or wait for 8 weeks", "description": "You can escalate to ADR once 8 weeks have passed since your original complaint, or sooner if {company_name} issues a deadlock letter. Check which ADR scheme your provider belongs to — this information is on Ofcom's website at ofcom.org.uk/phones-and-broadband/how-to-complain or on your provider's own complaints page.", "action_type": "info", "action_config": {"check_8_week_deadline": true, "tip": "Most providers are members of either CISAS (cedr.com/consumer/cisas) or Ombudsman Services: Communications (ombudsman-services.org/sectors/communications). Your provider must tell you which scheme they belong to if you ask. Check before proceeding so you submit to the correct scheme."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Tracking the 8-week deadline from your initial complaint. We will notify you when you are eligible to escalate.", "next_step": "adr-referral"},
  {"step_id": "adr-referral", "order": 9, "title": "Submit your ADR complaint", "description": "You are now eligible to escalate to Alternative Dispute Resolution. We have prepared your referral letter and a full case summary PDF with your timeline, speed test evidence, and correspondence history. Submit this to your provider's ADR scheme.", "action_type": "escalate", "action_config": {"letter_type": "adr_referral", "auto_generate": true, "prompt_context": "broadband_speed_adr", "export_pdf": true, "escalation_target": "CISAS or Ombudsman Services: Communications", "escalation_url": "https://www.ofcom.org.uk/phones-and-broadband/how-to-complain", "escalation_method": "Online form — check your provider's ADR scheme first"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "ADR decisions typically take 6-8 weeks. Log any correspondence you receive.", "next_step": "awaiting-adr"},
  {"step_id": "awaiting-adr", "order": 10, "title": "Await the ADR decision", "description": "Your complaint is now with the ADR scheme. They will investigate and issue a decision. The decision is binding on {company_name} if you accept it, but you are not obliged to accept — you can reject it and pursue the matter through the courts if you prefer.", "action_type": "wait", "action_config": {"tip": "If the ADR scheme finds in your favour, your provider must comply. Remedies can include fixing the service, allowing you to exit the contract, refunding charges, or paying compensation."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Well done for seeing this through. Record your outcome to help other broadband customers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
-- 11E-2: Flight Delay / Cancellation Compensation guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'flight-delay',
  'flight_delay',
  'Flight Delay or Cancellation Compensation',
  'Step-by-step guide to claiming compensation for a delayed or cancelled flight under UK261/EU261 regulations.',
  'travel',
  true,
  $steps$
[
  {"step_id": "check-eligibility", "order": 1, "title": "Check your eligibility", "description": "Not all flight delays qualify for compensation. Answer these questions to confirm your claim is valid before proceeding.", "action_type": "checklist", "action_config": {"items": ["Confirm your flight was delayed by 3 or more hours at your final destination (or was cancelled, or you were denied boarding)", "Confirm the flight departed from a UK or EU airport, OR arrived at a UK/EU airport on a UK/EU carrier", "Confirm the flight was within the last 6 years (5 years if you live in Scotland)", "Check whether the delay was caused by extraordinary circumstances (severe weather, air traffic control strike, volcanic ash, security threat) — if so, compensation may not be available, but you should still claim as airlines often cite this incorrectly", "Find your booking confirmation or e-ticket showing the flight number, date, and route"], "tip": "Technical faults, crew shortages, missed connecting flights due to the airline's scheduling, and IT failures are NOT extraordinary circumstances — the airline owes you compensation for these. Airlines frequently claim extraordinary circumstances incorrectly. If in doubt, proceed with the claim."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "calculate-compensation"},
  {"step_id": "calculate-compensation", "order": 2, "title": "Calculate your compensation", "description": "Your compensation amount depends on the flight distance. Use the TheyPromised compensation calculator to determine the amount, or refer to the standard rates: under 1,500km = £220, 1,500-3,500km = £350, over 3,500km = £520. Note: if you were offered re-routing that arrived within 2-4 hours of the original arrival time (depending on distance), the airline may reduce compensation by 50%.", "action_type": "info", "action_config": {"compensation_table": [{"distance": "Under 1,500km (short haul)", "amount": "£220 / €250"}, {"distance": "1,500 — 3,500km (medium haul)", "amount": "£350 / €400"}, {"distance": "Over 3,500km (long haul)", "amount": "£520 / €600"}], "tip": "Use a flight distance calculator (e.g. webflyer.com/travel/mileage_calculator) to check the great circle distance between your departure and arrival airports. This is the distance used for compensation, not the actual route flown."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "gather-evidence"},
  {"step_id": "gather-evidence", "order": 3, "title": "Gather your evidence", "description": "Collect all evidence related to your disrupted flight before sending your claim.", "action_type": "checklist", "action_config": {"items": ["Upload your booking confirmation or e-ticket", "Upload your boarding pass (if you have it)", "Note the actual departure and arrival times (check your airline's app, Flightradar24, or FlightAware for the actual times)", "Save any communication from the airline about the delay or cancellation (emails, SMS, app notifications)", "Keep receipts for any expenses incurred due to the delay (food, accommodation, transport) — you may be able to claim these separately under the airline's duty of care obligations", "If you were offered re-routing, note the alternative flight details and actual arrival time"]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-claim"},
  {"step_id": "initial-claim", "order": 4, "title": "Send your compensation claim", "description": "We have drafted a formal compensation claim to {company_name}. This letter cites your rights under UK261 (or EU261), specifies the compensation amount, and includes your flight details and evidence.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "flight_delay_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 28, "wait_message": "Airlines often take several weeks to respond to compensation claims. We have set a 28-day deadline. Many airlines have an online claims portal — if you submitted through their portal as well, log that interaction.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 5, "title": "How did the airline respond?", "description": "Check whether {company_name} has responded to your claim.", "action_type": "branch", "action_config": {"question": "What happened after your claim?", "options": [{"label": "They paid the full compensation", "next_step": "resolved"}, {"label": "They offered a partial amount or vouchers", "next_step": "reject-partial"}, {"label": "They refused, citing extraordinary circumstances", "next_step": "challenge-refusal"}, {"label": "No response", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "reject-partial", "order": 6, "title": "Reject the partial offer", "description": "Airlines sometimes offer vouchers, reduced amounts, or loyalty points instead of the cash compensation you are legally entitled to. You are under no obligation to accept these. UK261/EU261 entitles you to cash compensation at the fixed rates.", "action_type": "info", "action_config": {"tip": "Do not accept vouchers or reduced offers unless you are genuinely happy with them. Once you accept, it may be harder to claim the full amount. Your legal entitlement is cash compensation at the fixed rate, not vouchers or air miles."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "challenge-refusal", "order": 7, "title": "Challenge the extraordinary circumstances claim", "description": "The airline has claimed the delay was caused by extraordinary circumstances. This is the most common reason for refusal, and airlines frequently cite it incorrectly. Technical faults, crew shortages, IT failures, and operational issues are NOT extraordinary circumstances under established case law.", "action_type": "info", "action_config": {"tip": "Key case law: Huzar v Jet2 (2014) — technical faults are inherent in normal airline operations. Van der Lans v KLM (2015) — unexpected technical problems are not extraordinary circumstances. If the airline cited a technical fault, crew issue, or operational problem, their refusal is likely invalid."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "follow-up", "order": 8, "title": "Send a follow-up letter", "description": "This follow-up rejects any inadequate offer or challenges the airline's refusal. It references the relevant case law, restates your legal entitlement, and warns of ADR escalation.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "flight_delay_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 more days for {company_name} to reconsider. If they still refuse, you can escalate to ADR.", "next_step": "assess-response-2"},
  {"step_id": "assess-response-2", "order": 9, "title": "Final check before ADR", "description": "Has {company_name} paid your compensation?", "action_type": "branch", "action_config": {"question": "What happened after your follow-up?", "options": [{"label": "They paid the full amount", "next_step": "resolved"}, {"label": "Still refusing or no response", "next_step": "deadlock-or-8-weeks"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "deadlock-or-8-weeks"},
  {"step_id": "deadlock-or-8-weeks", "order": 10, "title": "Wait for 8 weeks or request a deadlock letter", "description": "You can escalate to ADR once 8 weeks have passed since your original claim. Most UK airlines use AviationADR (operated by CEDR). Check which ADR scheme {company_name} belongs to at aviationadr.org.uk or on the CAA website.", "action_type": "info", "action_config": {"check_8_week_deadline": true, "tip": "You can also complain to the CAA (Civil Aviation Authority) at caa.co.uk/passengers — they cannot award compensation directly but can investigate the airline and put pressure on them. Consider submitting a CAA complaint in parallel with your ADR referral."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Tracking the 8-week deadline. We will notify you when you can escalate.", "next_step": "adr-referral"},
  {"step_id": "adr-referral", "order": 11, "title": "Submit your ADR complaint", "description": "We have prepared your ADR referral with a complete case summary, all evidence, and your correspondence history. Submit this to AviationADR (or whichever scheme your airline belongs to).", "action_type": "escalate", "action_config": {"letter_type": "adr_referral", "auto_generate": true, "prompt_context": "flight_delay_adr", "export_pdf": true, "escalation_target": "AviationADR (CEDR)", "escalation_url": "https://www.aviationadr.org.uk/", "escalation_method": "Online form at aviationadr.org.uk"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "ADR typically takes 4-8 weeks. Log any correspondence.", "next_step": "awaiting-adr"},
  {"step_id": "awaiting-adr", "order": 12, "title": "Await the ADR decision", "description": "Your claim is now with the ADR scheme. Their decision is binding on {company_name} if you accept it. If you reject it, you can still take the airline to the small claims court. Most flight delay claims are straightforward and succeed at ADR if your evidence is solid.", "action_type": "wait", "action_config": {"tip": "If ADR rules in your favour and the airline still does not pay, you can enforce the decision through the county court. This is rare — airlines almost always comply with ADR decisions."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Record your outcome to help other air passengers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
-- 11E-3: Bank Charges dispute guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'bank-charges',
  'bank_charges',
  'Bank Charges Dispute',
  'Step-by-step guide to disputing unfair or incorrect bank charges, from formal complaint through to the Financial Ombudsman Service.',
  'finance',
  true,
  $steps$
[
  {"step_id": "gather-evidence", "order": 1, "title": "Gather your evidence", "description": "Before contacting your bank, collect all evidence of the charges you are disputing.", "action_type": "checklist", "action_config": {"items": ["Download or screenshot your bank statements showing the disputed charges — highlight or note the specific charges", "Calculate the total amount you believe was charged unfairly or incorrectly", "Check your account terms and conditions for the relevant fee schedule", "Note any previous communication with the bank about these charges", "If charges resulted from a bank error (e.g. failed to process a payment, applied the wrong interest rate), document the error and its impact"], "tip": "Request a full statement of charges from your bank if you need a longer history. Under the Data Protection Act 2018 (GDPR), they must provide this within one month, usually free of charge."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint"},
  {"step_id": "initial-complaint", "order": 2, "title": "Send your formal complaint", "description": "We have drafted a formal complaint to {company_name} disputing the charges and requesting a refund. This letter starts the 8-week clock for Financial Ombudsman eligibility.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "bank_charges_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Your bank should acknowledge your complaint within a few days. They have up to 8 weeks to provide a final response. Log any communication you receive.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 3, "title": "Has the bank responded?", "description": "Check whether {company_name} has acknowledged or responded to your complaint.", "action_type": "branch", "action_config": {"question": "What has happened so far?", "options": [{"label": "They refunded the charges in full", "next_step": "resolved"}, {"label": "They offered a partial refund", "next_step": "consider-partial"}, {"label": "They rejected my complaint", "next_step": "follow-up"}, {"label": "They acknowledged but have not resolved it yet", "next_step": "wait-for-final-response"}, {"label": "No response at all", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "consider-partial", "order": 4, "title": "Consider the partial offer", "description": "The bank has offered a partial refund. Consider whether this is acceptable. If the full amount is significant and you believe you are entitled to it, you can reject the offer and escalate. The Financial Ombudsman can award the full amount if your claim is valid.", "action_type": "info", "action_config": {"tip": "If the bank's partial offer is close to what you claimed and the remaining amount is small, it may be more practical to accept. If the gap is large, proceed with the follow-up and escalation. You will not be penalised by the Ombudsman for rejecting a partial offer."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "wait-for-final-response", "order": 5, "title": "Wait for the bank's final response", "description": "The bank has acknowledged your complaint and is investigating. Under FCA rules, they must send you a final response within 8 weeks. If they cannot resolve it within that time, they must send you a letter explaining why and telling you about your right to go to the Financial Ombudsman.", "action_type": "wait", "action_config": {"check_8_week_deadline": true, "tip": "If you receive a 'final response letter' before 8 weeks, read it carefully. If you are unhappy with the outcome, you have 6 months from the date of that letter to refer your complaint to the Financial Ombudsman."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Waiting for the bank's final response. The 8-week deadline is tracked automatically.", "next_step": "assess-final-response"},
  {"step_id": "assess-final-response", "order": 6, "title": "Review the bank's final response", "description": "The 8-week period has passed or you have received a final response letter. What happened?", "action_type": "branch", "action_config": {"question": "What is the current status?", "options": [{"label": "Resolved — I got a full refund", "next_step": "resolved"}, {"label": "Final response received but I am not satisfied", "next_step": "fos-referral"}, {"label": "8 weeks passed with no final response", "next_step": "fos-referral"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "fos-referral"},
  {"step_id": "follow-up", "order": 7, "title": "Send a follow-up letter", "description": "Your complaint was either rejected or ignored. This follow-up references the original complaint, challenges the bank's position, and warns of escalation to the Financial Ombudsman.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "bank_charges_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 more days for {company_name} to reconsider before escalation.", "next_step": "wait-for-final-response"},
  {"step_id": "fos-referral", "order": 8, "title": "Refer to the Financial Ombudsman Service", "description": "You are now eligible to escalate to the Financial Ombudsman Service (FOS). We have prepared your referral with a complete case summary, evidence, and correspondence history. FOS is free to use and their decisions are binding on the bank.", "action_type": "escalate", "action_config": {"letter_type": "ombudsman_referral", "auto_generate": true, "prompt_context": "bank_charges_fos", "export_pdf": true, "escalation_target": "Financial Ombudsman Service", "escalation_url": "https://www.financial-ombudsman.org.uk/consumers/how-to-complain", "escalation_method": "Online form, phone (0800 023 4567), or post"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "FOS investigations typically take several months. Log any correspondence. FOS may contact you for additional information or to discuss a settlement.", "next_step": "awaiting-fos"},
  {"step_id": "awaiting-fos", "order": 9, "title": "Await the Ombudsman decision", "description": "Your complaint is with the Financial Ombudsman Service. An adjudicator will review the case and make an initial assessment. If either side disagrees, an ombudsman will make a final decision. The decision is binding on the bank if you accept it.", "action_type": "wait", "action_config": {"tip": "FOS will first try to resolve the complaint informally. If the adjudicator's initial assessment goes against you, you can request a final decision from an ombudsman — this is a different, more senior person. Do not give up at the adjudicator stage if you believe your case is strong."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Record your outcome to help other bank customers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
-- 11E-4: Faulty Product (Consumer Rights Act 2015) guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'faulty-product',
  'faulty_product',
  'Faulty Product Complaint',
  'Step-by-step guide to getting a refund, repair, or replacement for a faulty product under the Consumer Rights Act 2015.',
  'retail',
  true,
  $steps$
[
  {"step_id": "assess-timeline", "order": 1, "title": "When did you buy the product?", "description": "Your rights depend on how long ago you bought the product. This determines which remedy you should pursue first.", "action_type": "branch", "action_config": {"question": "How long ago did you purchase the product?", "options": [{"label": "Less than 30 days ago", "next_step": "short-term-reject"}, {"label": "30 days to 6 months ago", "next_step": "repair-or-replace"}, {"label": "More than 6 months ago", "next_step": "long-term-claim"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "short-term-reject"},
  {"step_id": "short-term-reject", "order": 2, "title": "Exercise your short-term right to reject", "description": "You bought this product less than 30 days ago. Under section 22 of the Consumer Rights Act 2015, you have an absolute right to reject the goods for a full refund. The retailer cannot insist on a repair or replacement — you are entitled to your money back.", "action_type": "checklist", "action_config": {"items": ["Confirm the product is genuinely faulty, not as described, or not fit for purpose", "Find your proof of purchase (receipt, order confirmation email, bank statement showing the transaction)", "Upload photos or videos showing the fault", "Stop using the product if possible (continued use after discovering the fault could weaken your right to reject)"], "tip": "You do NOT need the original packaging. The retailer cannot refuse a return because you have lost the box. You just need proof of purchase."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-reject"},
  {"step_id": "repair-or-replace", "order": 3, "title": "Request a repair or replacement", "description": "Your product is between 30 days and 6 months old. Under the Consumer Rights Act 2015, you are entitled to a repair or replacement. The retailer must do this within a reasonable time and without significant inconvenience to you. If the first repair or replacement fails, you have the right to a price reduction or to reject the goods.", "action_type": "checklist", "action_config": {"items": ["Find your proof of purchase", "Upload photos or videos showing the fault", "Decide whether you want a repair or replacement (you can choose, but the retailer can refuse if your choice is disproportionately expensive compared to the alternative)", "Note: during this period, the burden of proof is on the retailer — the product is presumed to have been faulty at delivery unless they can prove otherwise"], "tip": "If the retailer claims the fault is due to misuse, they must prove it. You do not need to prove the product was faulty when you bought it during the first 6 months."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-repair"},
  {"step_id": "long-term-claim", "order": 4, "title": "Gather evidence of the inherent fault", "description": "Your product is more than 6 months old. You can still claim under the Consumer Rights Act 2015, but the burden of proof is now on you — you need to show that the fault was present at delivery or is due to an inherent defect in the product, not normal wear and tear or misuse.", "action_type": "checklist", "action_config": {"items": ["Find your proof of purchase", "Upload photos or videos showing the fault", "Consider whether the fault is clearly a manufacturing defect or inherent problem (e.g. a washing machine motor failing after 8 months is likely inherent; a cracked phone screen from being dropped is not)", "If the product is expensive, consider getting an independent expert report or opinion (this can strengthen your case but is not always necessary)", "Check online for other customers reporting the same fault — a known issue strengthens your position"], "tip": "Products should last a reasonable amount of time. A £1,200 laptop failing after 7 months is not reasonable even if the warranty has expired. Your statutory rights under the CRA are separate from any manufacturer warranty."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-repair"},
  {"step_id": "initial-complaint-reject", "order": 5, "title": "Send your rejection letter", "description": "We have drafted a formal letter to {company_name} rejecting the faulty goods and requesting a full refund under section 22 of the Consumer Rights Act 2015.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "faulty_product_reject"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Give {company_name} 14 days to process your refund. If they refuse or ignore you, we will help you escalate.", "next_step": "assess-response-1"},
  {"step_id": "initial-complaint-repair", "order": 6, "title": "Send your complaint requesting a remedy", "description": "We have drafted a formal complaint to {company_name} requesting a repair or replacement under the Consumer Rights Act 2015.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "faulty_product_repair"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 21, "wait_message": "Give {company_name} a reasonable time to arrange the repair or replacement. 21 days is generally considered reasonable. Log any communication.", "next_step": "assess-repair-response"},
  {"step_id": "assess-response-1", "order": 7, "title": "Did they accept the rejection?", "description": "Has {company_name} processed your refund?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Full refund received", "next_step": "resolved"}, {"label": "They offered a repair or replacement instead of a refund", "next_step": "insist-refund"}, {"label": "They refused entirely", "next_step": "follow-up-reject"}, {"label": "No response", "next_step": "follow-up-reject"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "insist-refund", "order": 8, "title": "You are entitled to a refund, not just a repair", "description": "Within the first 30 days, the retailer CANNOT insist on a repair or replacement. Your short-term right to reject is absolute under section 22 of the Consumer Rights Act 2015. The retailer is misstating your rights.", "action_type": "info", "action_config": {"tip": "This is one of the most common ways retailers try to avoid giving refunds. They will say 'our policy is to repair first' or 'we need to send it to the manufacturer.' Your statutory rights override any store policy. The law is clear: within 30 days, you choose the refund."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "assess-repair-response", "order": 9, "title": "Was the repair or replacement successful?", "description": "Did {company_name} repair or replace the product, and does it now work properly?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Repaired/replaced and working fine", "next_step": "resolved"}, {"label": "Repair failed — still faulty", "next_step": "final-right-to-reject"}, {"label": "They refused to repair or replace", "next_step": "follow-up-repair"}, {"label": "No response or unreasonable delay", "next_step": "follow-up-repair"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-repair"},
  {"step_id": "final-right-to-reject", "order": 10, "title": "Exercise your final right to reject", "description": "The first repair or replacement has failed. Under section 24 of the Consumer Rights Act 2015, you now have the final right to reject the goods for a refund (subject to a deduction for the use you have had) or to request a price reduction.", "action_type": "info", "action_config": {"tip": "The retailer can make a reasonable deduction for the use you have had of the product, but the deduction must be fair. For example, if a £500 washing machine failed after 4 months and the expected lifespan is 7 years, a fair deduction for use might be around £24 (4/84 months). The deduction cannot reduce your refund to zero."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "follow-up-reject", "order": 11, "title": "Send a follow-up insisting on your refund", "description": "This letter firmly restates your right to a refund, references the specific section of the Consumer Rights Act 2015, and warns of further action if the retailer does not comply.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "faulty_product_followup_reject"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 days for {company_name} to process the refund. If they still refuse, we will explore your escalation options.", "next_step": "escalation-options"},
  {"step_id": "follow-up-repair", "order": 12, "title": "Send a follow-up about the failed repair", "description": "This letter notes the retailer's failure to provide a timely repair or replacement and asserts your right to a price reduction or rejection.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "faulty_product_followup_repair"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 days for {company_name} to arrange a remedy.", "next_step": "escalation-options"},
  {"step_id": "escalation-options", "order": 13, "title": "Consider your escalation options", "description": "The retailer has refused to honour your consumer rights. Unlike energy, broadband, or banking, there is no ombudsman for general retail. Your options depend on how you paid and the value of the claim.", "action_type": "branch", "action_config": {"question": "How did you pay for the product?", "options": [{"label": "Credit card (and the item cost over £100)", "next_step": "section-75"}, {"label": "Debit card", "next_step": "chargeback"}, {"label": "Cash, bank transfer, or other", "next_step": "small-claims"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "small-claims"},
  {"step_id": "section-75", "order": 14, "title": "Make a Section 75 claim with your credit card provider", "description": "If you paid by credit card and the item cost between £100 and £30,000, your credit card provider is jointly liable for the breach of contract under section 75 of the Consumer Credit Act 1974. This means you can claim the refund from your card provider instead of (or as well as) the retailer.", "action_type": "send_letter", "action_config": {"letter_type": "section_75_claim", "auto_generate": true, "prompt_context": "faulty_product_section75"}, "completion_criteria": {"type": "letter_sent", "letter_type": "section_75_claim"}, "wait_after_days": 28, "wait_message": "Card providers typically take 2-4 weeks to process Section 75 claims. If they refuse, you can escalate to the Financial Ombudsman Service.", "next_step": "assess-section-75"},
  {"step_id": "chargeback", "order": 15, "title": "Request a chargeback from your bank", "description": "If you paid by debit card, you can request a chargeback through your bank. This is not a statutory right (it is a scheme rule from Visa/Mastercard), but banks generally process these. Contact your bank and explain that the retailer has breached the Consumer Rights Act 2015 by refusing to remedy a faulty product.", "action_type": "info", "action_config": {"tip": "Chargebacks usually must be initiated within 120 days of the transaction (or 120 days from when you discovered the fault, depending on the card scheme). Act quickly. If the chargeback fails or is disputed by the retailer, the small claims court is your next option."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "small-claims"},
  {"step_id": "assess-section-75", "order": 16, "title": "Did the card provider refund you?", "description": "What was the outcome of your Section 75 claim?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Refund received", "next_step": "resolved"}, {"label": "Claim rejected — I want to escalate", "next_step": "fos-section75"}, {"label": "Still waiting", "next_step": "assess-section-75"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "fos-section75"},
  {"step_id": "fos-section75", "order": 17, "title": "Escalate to the Financial Ombudsman", "description": "Your credit card provider rejected your Section 75 claim. Because they are an FCA-regulated firm, you can escalate to the Financial Ombudsman Service. Follow the same 8-week complaint process as for a bank complaint.", "action_type": "escalate", "action_config": {"letter_type": "ombudsman_referral", "auto_generate": true, "prompt_context": "faulty_product_fos_s75", "export_pdf": true, "escalation_target": "Financial Ombudsman Service", "escalation_url": "https://www.financial-ombudsman.org.uk/consumers/how-to-complain", "escalation_method": "Online form, phone (0800 023 4567), or post"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "small-claims", "order": 18, "title": "Consider the small claims court", "description": "If the retailer continues to refuse and other options are exhausted, you can take them to the small claims court. For claims up to £10,000 in England and Wales, the process is straightforward and designed for individuals without legal representation. Court fees are modest and proportional to the claim amount.", "action_type": "info", "action_config": {"tip": "Small claims court fees: claims up to £300 cost £35, up to £500 cost £50, up to £1,000 cost £70, up to £1,500 cost £80, up to £3,000 cost £115, up to £5,000 cost £205, up to £10,000 cost £455. You can claim these fees back if you win. Most retailers settle once they receive a court claim because defending is more expensive than refunding. You can start a claim online at moneyclaims.service.gov.uk.", "escalation_url": "https://www.gov.uk/make-court-claim-for-money", "letter_before_action": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "letter-before-action"},
  {"step_id": "letter-before-action", "order": 19, "title": "Send a Letter Before Action", "description": "Before starting court proceedings, you must send a formal 'Letter Before Action' (also called a 'Letter Before Claim'). This gives the retailer a final 14-day deadline to resolve the matter. Courts expect you to have attempted this step, and many retailers settle at this point because they know you are serious.", "action_type": "send_letter", "action_config": {"letter_type": "letter_before_action", "auto_generate": true, "prompt_context": "faulty_product_lba"}, "completion_criteria": {"type": "letter_sent", "letter_type": "letter_before_action"}, "wait_after_days": 14, "wait_message": "This is the retailer's final chance. Many companies settle at this stage to avoid court. If they do not respond within 14 days, you can proceed with a court claim.", "next_step": "assess-lba-response"},
  {"step_id": "assess-lba-response", "order": 20, "title": "Did the retailer respond to the Letter Before Action?", "description": "What happened after your Letter Before Action?", "action_type": "branch", "action_config": {"question": "Outcome?", "options": [{"label": "They refunded or settled", "next_step": "resolved"}, {"label": "No response or refusal — I want to proceed to court", "next_step": "court-claim"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "court-claim"},
  {"step_id": "court-claim", "order": 21, "title": "Start your court claim", "description": "You can now submit a claim through the Money Claims Online service. Your TheyPromised case file, timeline, and correspondence form the evidence for your claim. Export your case PDF and keep all letters and responses available.", "action_type": "escalate", "action_config": {"export_pdf": true, "escalation_target": "Small Claims Court (County Court)", "escalation_url": "https://www.gov.uk/make-court-claim-for-money", "escalation_method": "Online at moneyclaims.service.gov.uk"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Well done for standing up for your consumer rights. Record your outcome to help others know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
