import type { OrganisationInsert } from "@/types/database";

export const SEED_ORGANISATIONS: OrganisationInsert[] = [
  // ── ENERGY ─────────────────────────────────────────────────────────────────
  {
    name: "British Gas",
    category: "energy",
    website: "https://www.britishgas.co.uk",
    complaint_email: "customerservices@britishgas.co.uk",
    complaint_phone: "0333 202 9802",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "EDF Energy",
    category: "energy",
    website: "https://www.edfenergy.com",
    complaint_email: "customer.services@edfenergy.com",
    complaint_phone: "0333 200 5100",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "OVO Energy",
    category: "energy",
    website: "https://www.ovoenergy.com",
    complaint_email: "customer.services@ovoenergy.com",
    complaint_phone: "0330 303 5063",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Octopus Energy",
    category: "energy",
    website: "https://octopus.energy",
    complaint_email: "hello@octopus.energy",
    complaint_phone: "0808 164 1088",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Scottish Power",
    category: "energy",
    website: "https://www.scottishpower.co.uk",
    complaint_phone: "0800 074 1974",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Shell Energy",
    category: "energy",
    website: "https://www.shellenergy.co.uk",
    complaint_phone: "0800 049 8484",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "E.ON Next",
    category: "energy",
    website: "https://www.eonnext.com",
    complaint_phone: "0808 501 5200",
    ombudsman_name: "Energy Ombudsman (Ombudsman Services: Energy)",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/energy",
    escalation_wait_weeks: 8,
    is_verified: true,
  },

  // ── BROADBAND & PHONE ──────────────────────────────────────────────────────
  {
    name: "BT",
    category: "broadband_phone",
    website: "https://www.bt.com",
    complaint_phone: "0800 800 150",
    ombudsman_name: "Ombudsman Services: Communications",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/communications",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Sky",
    category: "broadband_phone",
    website: "https://www.sky.com",
    complaint_phone: "0333 759 3001",
    ombudsman_name: "CISAS",
    ombudsman_url: "https://www.commsombudsman.org/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Virgin Media O2",
    category: "broadband_phone",
    website: "https://www.virginmedia.com",
    complaint_phone: "0345 454 1111",
    ombudsman_name: "CISAS",
    ombudsman_url: "https://www.commsombudsman.org/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "TalkTalk",
    category: "broadband_phone",
    website: "https://www.talktalk.co.uk",
    complaint_email: "customercomplaints@talktalk.com",
    complaint_phone: "0345 172 0088",
    ombudsman_name: "CISAS",
    ombudsman_url: "https://www.commsombudsman.org/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Vodafone",
    category: "broadband_phone",
    website: "https://www.vodafone.co.uk",
    complaint_phone: "0333 304 0191",
    ombudsman_name: "Ombudsman Services: Communications",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/communications",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Three",
    category: "broadband_phone",
    website: "https://www.three.co.uk",
    complaint_phone: "0333 338 1001",
    ombudsman_name: "CISAS",
    ombudsman_url: "https://www.commsombudsman.org/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "EE",
    category: "broadband_phone",
    website: "https://ee.co.uk",
    complaint_phone: "0800 956 6000",
    ombudsman_name: "Ombudsman Services: Communications",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/communications",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Plusnet",
    category: "broadband_phone",
    website: "https://www.plus.net",
    complaint_phone: "0800 432 0200",
    ombudsman_name: "Ombudsman Services: Communications",
    ombudsman_url: "https://www.ombudsman-services.org/sectors/communications",
    escalation_wait_weeks: 8,
    is_verified: true,
  },

  // ── BANKS ─────────────────────────────────────────────────────────────────
  {
    name: "HSBC",
    category: "financial_services",
    website: "https://www.hsbc.co.uk",
    complaint_phone: "0800 085 2401",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Barclays",
    category: "financial_services",
    website: "https://www.barclays.co.uk",
    complaint_phone: "0800 282 390",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Lloyds Bank",
    category: "financial_services",
    website: "https://www.lloydsbank.com",
    complaint_phone: "0800 072 3572",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "NatWest",
    category: "financial_services",
    website: "https://www.natwest.com",
    complaint_phone: "0800 161 5154",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Santander",
    category: "financial_services",
    website: "https://www.santander.co.uk",
    complaint_phone: "0800 731 6893",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Nationwide Building Society",
    category: "financial_services",
    website: "https://www.nationwide.co.uk",
    complaint_phone: "0800 302 010",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Monzo",
    category: "financial_services",
    website: "https://monzo.com",
    complaint_email: "complaints@monzo.com",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Starling Bank",
    category: "financial_services",
    website: "https://www.starlingbank.com",
    complaint_email: "complaints@starlingbank.com",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },

  // ── INSURANCE ─────────────────────────────────────────────────────────────
  {
    name: "Aviva",
    category: "insurance",
    website: "https://www.aviva.co.uk",
    complaint_phone: "0800 015 1142",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Direct Line",
    category: "insurance",
    website: "https://www.directline.com",
    complaint_phone: "0345 246 8704",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Admiral",
    category: "insurance",
    website: "https://www.admiral.com",
    complaint_phone: "0333 220 2000",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "LV= (Liverpool Victoria)",
    category: "insurance",
    website: "https://www.lv.com",
    complaint_phone: "0800 678 1906",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },
  {
    name: "Saga",
    category: "insurance",
    website: "https://www.saga.co.uk",
    complaint_phone: "0800 056 5898",
    ombudsman_name: "Financial Ombudsman Service",
    ombudsman_url: "https://www.financial-ombudsman.org.uk/",
    escalation_wait_weeks: 8,
    is_verified: true,
  },

  // ── GOVERNMENT ────────────────────────────────────────────────────────────
  {
    name: "HMRC",
    category: "government_hmrc",
    website: "https://www.gov.uk/contact-hmrc",
    complaint_address: "HMRC, BX9 1AB",
    ombudsman_name: "The Adjudicator's Office",
    ombudsman_url: "https://www.adjudicatorsoffice.gov.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
    notes: "Complain via gov.uk/complain-about-hmrc. After HMRC internal process, escalate to Adjudicator's Office.",
  },
  {
    name: "DWP (Department for Work and Pensions)",
    category: "government_dwp",
    website: "https://www.gov.uk/contact-dwp",
    ombudsman_name: "Parliamentary and Health Service Ombudsman (via MP)",
    ombudsman_url: "https://www.ombudsman.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
    notes: "For benefit decisions, use Mandatory Reconsideration first (1-month deadline).",
  },
  {
    name: "NHS England",
    category: "nhs",
    website: "https://www.england.nhs.uk/contact-us/complaint/",
    ombudsman_name: "Parliamentary and Health Service Ombudsman",
    ombudsman_url: "https://www.ombudsman.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
    notes: "Contact PALS first, then formal complaint to the NHS provider.",
  },

  // ── RETAIL ────────────────────────────────────────────────────────────────
  {
    name: "Amazon UK",
    category: "retail",
    website: "https://www.amazon.co.uk",
    complaint_address: "Amazon UK Services Ltd, 1 Principal Place, London EC2A 2FA",
    ombudsman_name: "Small Claims Court (MCOL)",
    ombudsman_url: "https://www.gov.uk/make-court-claim-for-money",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "Currys",
    category: "retail",
    website: "https://www.currys.co.uk",
    complaint_email: "customerservices@currys.co.uk",
    complaint_phone: "0344 561 1234",
    ombudsman_name: "Small Claims Court (MCOL)",
    ombudsman_url: "https://www.gov.uk/make-court-claim-for-money",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "Argos",
    category: "retail",
    website: "https://www.argos.co.uk",
    complaint_phone: "0345 165 7910",
    ombudsman_name: "Small Claims Court (MCOL)",
    ombudsman_url: "https://www.gov.uk/make-court-claim-for-money",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "John Lewis",
    category: "retail",
    website: "https://www.johnlewis.com",
    complaint_phone: "0330 123 3550",
    ombudsman_name: "Small Claims Court (MCOL)",
    ombudsman_url: "https://www.gov.uk/make-court-claim-for-money",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "ASOS",
    category: "retail",
    website: "https://www.asos.com",
    complaint_email: "customercare@asos.com",
    ombudsman_name: "Small Claims Court (MCOL)",
    ombudsman_url: "https://www.gov.uk/make-court-claim-for-money",
    escalation_wait_weeks: null,
    is_verified: true,
  },

  // ── TRANSPORT ─────────────────────────────────────────────────────────────
  {
    name: "National Rail",
    category: "transport",
    website: "https://www.nationalrail.co.uk",
    ombudsman_name: "Rail Ombudsman",
    ombudsman_url: "https://www.railombudsman.org/",
    escalation_wait_weeks: 8,
    is_verified: true,
    notes: "Complain to the specific train operator first. After 40 working days, refer to Rail Ombudsman.",
  },
  {
    name: "Transport for London (TfL)",
    category: "transport",
    website: "https://tfl.gov.uk",
    complaint_phone: "0343 222 1234",
    ombudsman_name: "London TravelWatch",
    ombudsman_url: "https://londontravelwatch.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "DVLA",
    category: "transport",
    website: "https://www.gov.uk/contact-the-dvla",
    ombudsman_name: "Parliamentary and Health Service Ombudsman (via MP)",
    ombudsman_url: "https://www.ombudsman.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
  },

  // ── WATER ─────────────────────────────────────────────────────────────────
  {
    name: "Thames Water",
    category: "water",
    website: "https://www.thameswater.co.uk",
    complaint_email: "customer.helpline@thameswater.co.uk",
    complaint_phone: "0800 316 9800",
    ombudsman_name: "Consumer Council for Water (CCW)",
    ombudsman_url: "https://www.ccwater.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "United Utilities",
    category: "water",
    website: "https://www.unitedutilities.com",
    complaint_phone: "0345 672 2999",
    ombudsman_name: "Consumer Council for Water (CCW)",
    ombudsman_url: "https://www.ccwater.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
  },
  {
    name: "Anglian Water",
    category: "water",
    website: "https://www.anglianwater.co.uk",
    complaint_phone: "0800 145 145",
    ombudsman_name: "Consumer Council for Water (CCW)",
    ombudsman_url: "https://www.ccwater.org.uk/",
    escalation_wait_weeks: null,
    is_verified: true,
  },
];

export async function seedOrganisations(supabaseClient: {
  from: (table: string) => {
    upsert: (
      data: OrganisationInsert[],
      options: { onConflict: string }
    ) => Promise<{ error: { message: string } | null }>;
  };
}) {
  const { error } = await supabaseClient
    .from("organisations")
    .upsert(SEED_ORGANISATIONS, { onConflict: "name" });

  if (error) {
    throw new Error(`Failed to seed organisations: ${error.message}`);
  }

  return { seeded: SEED_ORGANISATIONS.length };
}
