import type { JourneyTemplate } from "@/types/journey";

// Map case categories to journey template IDs
export const CATEGORY_TO_JOURNEY: Record<string, string> = {
  energy: "energy-billing",
  broadband_phone: "broadband-speed",
  transport: "flight-delay",
  financial_services: "bank-charges",
  retail: "faulty-product",
};

export function getJourneyTemplateIdForCategory(category: string): string | null {
  return CATEGORY_TO_JOURNEY[category] ?? null;
}

// ── Template definitions ───────────────────────────────────────────────────────

const ENERGY_BILLING: JourneyTemplate = {
  id: "energy-billing",
  name: "Energy Billing Dispute",
  description: "Step-by-step guide to resolving an energy billing error, from initial complaint through to the Energy Ombudsman.",
  category: "energy",
  estimated_duration_days: 70,
  steps: [
    {
      step_id: "gather-evidence",
      order: 1,
      title: "Gather Your Evidence",
      description: "Before you write to {company_name}, make sure you have everything in order. Good evidence is the difference between winning and losing.",
      action_type: "checklist",
      action_config: {
        items: [
          "Collect all recent bills showing the billing error",
          "Find your original tariff confirmation email or letter",
          "Note the exact dates and amounts overcharged",
          "Screenshot your online account showing the incorrect rate",
          "Calculate the total overcharge to the nearest pound",
          "Gather any previous correspondence with {company_name}",
        ],
        tip: "The more specific you are about dates and amounts, the harder it is for {company_name} to dismiss your complaint. Include your account number in every letter.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-initial",
    },
    {
      step_id: "send-initial",
      order: 2,
      title: "Send Your Formal Complaint Letter",
      description: "Send a formal written complaint to {company_name}. This starts the official 8-week clock — after which you can escalate to the Energy Ombudsman.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "energy_billing_initial",
        tip: "Send by email and keep a copy. Note the date and any complaint reference number you receive.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "wait-response-1",
      order: 3,
      title: "Wait for {company_name}'s Response",
      description: "{company_name} has 14 days to acknowledge your complaint and 8 weeks to resolve it.",
      action_type: "wait",
      action_config: {
        wait_message: "Waiting for {company_name} to respond to your complaint. They should acknowledge within 14 days.",
        tip: "If you hear back sooner, you can skip this wait and move to the next step.",
      },
      completion_criteria: { type: "days_passed", days: 14 },
      wait_after_days: 14,
      wait_message: "Waiting for {company_name} to respond (14 days)",
      next_step: "response-check-1",
    },
    {
      step_id: "response-check-1",
      order: 4,
      title: "Did {company_name} Respond?",
      description: "Choose the option that best describes what happened after you sent your initial complaint.",
      action_type: "branch",
      action_config: {
        question: "What happened after you sent your complaint to {company_name}?",
        options: [
          {
            label: "They resolved my complaint — I'm satisfied",
            next_step: "resolve",
          },
          {
            label: "They responded but didn't resolve it (rejected, partial offer, or unsatisfactory)",
            next_step: "send-followup",
          },
          {
            label: "No response after 14+ days",
            next_step: "send-followup",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-followup",
    },
    {
      step_id: "send-followup",
      order: 5,
      title: "Send a Follow-Up Complaint Letter",
      description: "Chase {company_name} with a firmer follow-up letter. Reference your original complaint date and make clear you are approaching the 8-week deadline.",
      action_type: "send_letter",
      action_config: {
        letter_type: "follow_up",
        auto_generate: true,
        prompt_context: "energy_billing_followup",
        tip: "This letter should be firmer in tone. Explicitly mention the Energy Ombudsman and the 8-week deadline.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "follow_up" },
      wait_after_days: 0,
      next_step: "deadline-check",
    },
    {
      step_id: "deadline-check",
      order: 6,
      title: "Check Your 8-Week Escalation Deadline",
      description: "UK energy suppliers must resolve complaints within 8 weeks of the formal complaint. After this — or if they issue a 'deadlock' letter — you can refer your case to the Energy Ombudsman for free.",
      action_type: "info",
      action_config: {
        check_8_week_deadline: true,
        tip: "You can also escalate early if {company_name} sends you a 'deadlock' or 'final response' letter — this means they've given their final answer and you can go straight to the ombudsman.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "ombudsman-letter",
    },
    {
      step_id: "ombudsman-letter",
      order: 7,
      title: "Draft Your Ombudsman Referral Letter",
      description: "Prepare a structured summary of your complaint to submit to the Energy Ombudsman. This letter needs to cover the full chronology of your dispute.",
      action_type: "send_letter",
      action_config: {
        letter_type: "ombudsman_referral",
        auto_generate: true,
        prompt_context: "energy_billing_ombudsman",
        tip: "The Energy Ombudsman can award up to £10,000 in compensation. Be thorough — include every date, reference number, and broken promise.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-ombudsman",
    },
    {
      step_id: "escalate-ombudsman",
      order: 8,
      title: "Submit to the Energy Ombudsman",
      description: "Submit your complaint and supporting documents to the Energy Ombudsman. The service is free, independent, and can compel {company_name} to pay compensation.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "Energy Ombudsman",
        escalation_url: "https://www.energyombudsman.org",
        escalation_method: "Online portal or post",
        tip: "You'll need your case PDF and the Ombudsman referral letter. The Energy Ombudsman typically takes 3-4 months to resolve cases.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "resolve",
      order: 9,
      title: "Record the Outcome",
      description: "Well done for seeing this through. Record how your complaint was resolved so TheyPromised can track outcomes.",
      action_type: "resolve",
      action_config: {
        trigger_outcome_form: true,
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: null,
    },
  ],
};

const BROADBAND_SPEED: JourneyTemplate = {
  id: "broadband-speed",
  name: "Broadband Speed Dispute",
  description: "Step-by-step guide to resolving a broadband speed complaint, from initial complaint through to ADR (Alternative Dispute Resolution).",
  category: "broadband_phone",
  estimated_duration_days: 70,
  steps: [
    {
      step_id: "gather-evidence",
      order: 1,
      title: "Gather Speed Test Evidence",
      description: "You need documented proof that your speeds are consistently below the minimum guaranteed in your contract.",
      action_type: "checklist",
      action_config: {
        items: [
          "Run at least 3 speed tests per day for 3 days (at different times)",
          "Use a wired Ethernet connection for the most accurate results",
          "Screenshot each result with the timestamp visible",
          "Find your contract showing the 'minimum guaranteed speed'",
          "Note the dates and times of any full outages",
          "Gather any previous support tickets or reference numbers",
        ],
        tip: "Ofcom's code requires providers to tell you your guaranteed minimum speed at point of sale. Check your original order confirmation email.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-initial",
    },
    {
      step_id: "send-initial",
      order: 2,
      title: "Send Your Formal Complaint Letter",
      description: "Send a formal complaint to {company_name} citing your speed test evidence and the Ofcom Voluntary Code of Practice on Broadband Speeds.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "broadband_speed_initial",
        tip: "Under Ofcom's code, if speeds are below the guaranteed minimum after investigation, {company_name} must let you exit your contract penalty-free.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "wait-response-1",
      order: 3,
      title: "Wait for {company_name}'s Response",
      description: "{company_name} may send an engineer or run remote diagnostics. Wait at least 14 days for a response.",
      action_type: "wait",
      action_config: {
        wait_message: "Waiting for {company_name} to respond. They may contact you to arrange an engineer visit or run remote checks.",
        tip: "If an engineer visits and finds no fault but speeds remain slow, that strengthens your case for escalation.",
      },
      completion_criteria: { type: "days_passed", days: 14 },
      wait_after_days: 14,
      wait_message: "Waiting for {company_name} to respond (14 days)",
      next_step: "response-check-1",
    },
    {
      step_id: "response-check-1",
      order: 4,
      title: "Is Your Speed Issue Resolved?",
      description: "Choose the option that best describes what happened.",
      action_type: "branch",
      action_config: {
        question: "What happened after your initial complaint to {company_name}?",
        options: [
          {
            label: "My speed issue is fixed — complaint resolved",
            next_step: "resolve",
          },
          {
            label: "Engineer visited / diagnostics run but speeds are still slow",
            next_step: "send-followup",
          },
          {
            label: "No response or action after 14+ days",
            next_step: "send-followup",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-followup",
    },
    {
      step_id: "send-followup",
      order: 5,
      title: "Send a Follow-Up Letter",
      description: "Escalate your complaint with a firmer follow-up referencing the failed fix and your right to exit the contract under Ofcom's code.",
      action_type: "send_letter",
      action_config: {
        letter_type: "follow_up",
        auto_generate: true,
        prompt_context: "broadband_speed_followup",
        tip: "Explicitly demand either a resolution or written confirmation that you can exit the contract without penalty.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "follow_up" },
      wait_after_days: 0,
      next_step: "deadline-check",
    },
    {
      step_id: "deadline-check",
      order: 6,
      title: "Check Your 8-Week Escalation Deadline",
      description: "After 8 weeks from your formal complaint (or on receipt of a deadlock letter), you can refer your case to an Alternative Dispute Resolution (ADR) scheme — either CISAS or the Communications Ombudsman — for free.",
      action_type: "info",
      action_config: {
        check_8_week_deadline: true,
        tip: "Check which ADR scheme your provider uses: BT, Sky, TalkTalk, and Virgin Media use CISAS. EE and some others use the Communications Ombudsman.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "adr-letter",
    },
    {
      step_id: "adr-letter",
      order: 7,
      title: "Draft Your ADR Referral Submission",
      description: "Prepare a structured submission for your ADR scheme. This should cover the full complaint chronology, speed test evidence, and the outcome you are seeking.",
      action_type: "send_letter",
      action_config: {
        letter_type: "adr_referral",
        auto_generate: true,
        prompt_context: "broadband_speed_adr",
        tip: "Include your speed test screenshots and any engineer visit records as attachments when you submit.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-adr",
    },
    {
      step_id: "escalate-adr",
      order: 8,
      title: "Submit to ADR",
      description: "Submit your complaint to the relevant ADR scheme. Include your full case PDF and the ADR submission letter.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "CISAS / Communications Ombudsman",
        escalation_url: "https://www.cisas.org.uk",
        escalation_method: "Online portal",
        tip: "Check which scheme your provider is registered with before submitting. Submitting to the wrong scheme will delay your case.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "resolve",
      order: 9,
      title: "Record the Outcome",
      description: "Record how your broadband complaint was resolved.",
      action_type: "resolve",
      action_config: { trigger_outcome_form: true },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: null,
    },
  ],
};

const FLIGHT_DELAY: JourneyTemplate = {
  id: "flight-delay",
  name: "Flight Delay or Cancellation Compensation",
  description: "Step-by-step guide to claiming compensation for a delayed or cancelled flight under UK Regulation 261/2004.",
  category: "transport",
  estimated_duration_days: 84,
  steps: [
    {
      step_id: "know-your-rights",
      order: 1,
      title: "Know Your Rights Under UK261",
      description: "UK passengers are protected by UK261 (retained EU Regulation 261/2004). You may be owed fixed compensation plus care and assistance depending on the delay length and flight distance.",
      action_type: "info",
      action_config: {
        compensation_table: [
          { distance: "Under 1,500km (e.g. London–Amsterdam)", amount: "£220" },
          { distance: "1,500km–3,500km (e.g. London–Madrid)", amount: "£350" },
          { distance: "Over 3,500km (e.g. London–New York)", amount: "£520" },
        ],
        tip: "Compensation applies if your flight arrived 3+ hours late OR was cancelled with less than 14 days' notice. Airlines must prove 'extraordinary circumstances' to avoid paying — technical faults do NOT count.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-initial",
    },
    {
      step_id: "send-initial",
      order: 2,
      title: "Send Your Compensation Claim Letter",
      description: "Send a formal compensation claim to {company_name} citing UK261, your specific flight details, and the exact compensation amount you are claiming.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "flight_delay_initial",
        tip: "Include your flight number, booking reference, booked departure and arrival times, and actual arrival time. This is a legal claim, not a general complaint.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "wait-response-1",
      order: 3,
      title: "Wait for {company_name}'s Response",
      description: "Airlines typically take 28 days to respond to compensation claims. Wait for their response before escalating.",
      action_type: "wait",
      action_config: {
        wait_message: "Waiting for {company_name} to respond to your UK261 compensation claim.",
        tip: "Airlines sometimes offer vouchers instead of cash. You are legally entitled to cash — vouchers are not an acceptable substitute.",
      },
      completion_criteria: { type: "days_passed", days: 28 },
      wait_after_days: 28,
      wait_message: "Waiting for {company_name} to respond (28 days)",
      next_step: "response-check-1",
    },
    {
      step_id: "response-check-1",
      order: 4,
      title: "How Did {company_name} Respond?",
      description: "Airlines often initially reject or undervalue claims. Choose what happened.",
      action_type: "branch",
      action_config: {
        question: "What was {company_name}'s response to your compensation claim?",
        options: [
          {
            label: "They paid the correct cash compensation — resolved",
            next_step: "resolve",
          },
          {
            label: "They rejected my claim (extraordinary circumstances, vouchers, or underpaid)",
            next_step: "send-followup",
          },
          {
            label: "No response after 28 days",
            next_step: "send-followup",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-followup",
    },
    {
      step_id: "send-followup",
      order: 5,
      title: "Challenge Their Refusal or Silence",
      description: "Send a follow-up letter challenging any rejection on 'extraordinary circumstances' grounds or demanding a response.",
      action_type: "send_letter",
      action_config: {
        letter_type: "follow_up",
        auto_generate: true,
        prompt_context: "flight_delay_followup",
        tip: "If they claimed extraordinary circumstances, reference Huzar v Jet2.com Ltd [2014] establishing that technical faults are NOT extraordinary circumstances.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "follow_up" },
      wait_after_days: 0,
      next_step: "deadline-check",
    },
    {
      step_id: "deadline-check",
      order: 6,
      title: "Check Your 8-Week ADR Deadline",
      description: "After 8 weeks from your original claim (or receipt of a final response), you can refer your case to an Alternative Dispute Resolution scheme.",
      action_type: "info",
      action_config: {
        check_8_week_deadline: true,
        tip: "For flight compensation, the main ADR schemes are AviationADR and CEDR. Check which your airline uses. You can also pursue claims through MCOL (Money Claim Online) if you prefer the courts.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "adr-letter",
    },
    {
      step_id: "adr-letter",
      order: 7,
      title: "Draft Your ADR Submission",
      description: "Prepare a structured submission for the aviation ADR scheme, covering the full claim chronology, the airline's rejection, and your legal basis.",
      action_type: "send_letter",
      action_config: {
        letter_type: "adr_referral",
        auto_generate: true,
        prompt_context: "flight_delay_adr",
        tip: "Include your boarding pass, booking confirmation, and any evidence the airline sent claiming extraordinary circumstances.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-adr",
    },
    {
      step_id: "escalate-adr",
      order: 8,
      title: "Submit to ADR",
      description: "Submit your claim to AviationADR or CEDR. Include all supporting documents.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "AviationADR / CEDR",
        escalation_url: "https://www.aviationadr.org.uk",
        escalation_method: "Online portal",
        tip: "If your airline is not registered with an ADR scheme, you can take the claim directly to the County Court via Money Claim Online (MCOL) at www.gov.uk/make-court-claim-for-money.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "resolve",
      order: 9,
      title: "Record the Outcome",
      description: "Record how your flight compensation claim was resolved.",
      action_type: "resolve",
      action_config: { trigger_outcome_form: true },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: null,
    },
  ],
};

const BANK_CHARGES: JourneyTemplate = {
  id: "bank-charges",
  name: "Bank Charges Dispute",
  description: "Step-by-step guide to disputing unfair or incorrect bank charges, from initial complaint through to the Financial Ombudsman Service.",
  category: "financial_services",
  estimated_duration_days: 84,
  steps: [
    {
      step_id: "gather-evidence",
      order: 1,
      title: "Gather Your Evidence",
      description: "Compile a complete record of all disputed charges before contacting {company_name}.",
      action_type: "checklist",
      action_config: {
        items: [
          "Download or print all bank statements showing the disputed charges",
          "List every charge with date, amount, and description",
          "Calculate the total amount you are disputing",
          "Note any charges that resulted from a bank error or unclear terms",
          "Gather any letters, emails, or notifications about the charges",
          "Check your original account terms and conditions",
        ],
        tip: "Since April 2020, banks must charge a simple annual interest rate for unarranged overdrafts — no more fixed daily fees. Check if your charges predate this rule.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-initial",
    },
    {
      step_id: "send-initial",
      order: 2,
      title: "Send Your Formal Complaint Letter",
      description: "Send a formal complaint to {company_name} detailing each disputed charge and demanding a full refund.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "bank_charges_initial",
        tip: "Cite the FCA Consumer Duty (PS22/9) — banks must treat customers fairly and charges must be proportionate. If charges caused financial difficulty, mention this.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "wait-response-1",
      order: 3,
      title: "Wait for {company_name}'s Response",
      description: "Banks are required by FCA rules to acknowledge complaints within 5 business days and respond within 8 weeks.",
      action_type: "wait",
      action_config: {
        wait_message: "Waiting for {company_name} to respond to your charges dispute.",
        tip: "If {company_name} sends a holding response saying they need more time, note the date — the 8-week clock is still running.",
      },
      completion_criteria: { type: "days_passed", days: 14 },
      wait_after_days: 14,
      wait_message: "Waiting for {company_name} to respond (14 days)",
      next_step: "response-check-1",
    },
    {
      step_id: "response-check-1",
      order: 4,
      title: "How Did {company_name} Respond?",
      description: "Choose the option that best describes their response.",
      action_type: "branch",
      action_config: {
        question: "What was {company_name}'s response to your charges dispute?",
        options: [
          {
            label: "They agreed and refunded all disputed charges — resolved",
            next_step: "resolve",
          },
          {
            label: "They rejected my complaint or offered only a partial refund",
            next_step: "send-followup",
          },
          {
            label: "No response after 14+ days",
            next_step: "send-followup",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "send-followup",
    },
    {
      step_id: "send-followup",
      order: 5,
      title: "Send a Follow-Up Complaint Letter",
      description: "Challenge {company_name}'s rejection or push for the full amount if they offered only a partial refund.",
      action_type: "send_letter",
      action_config: {
        letter_type: "follow_up",
        auto_generate: true,
        prompt_context: "bank_charges_followup",
        tip: "Reference the FCA's DISP rules — banks must issue a final response within 8 weeks. Mention that you will refer to the Financial Ombudsman if unresolved.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "follow_up" },
      wait_after_days: 0,
      next_step: "deadline-check",
    },
    {
      step_id: "deadline-check",
      order: 6,
      title: "Check Your FOS Deadline",
      description: "After 8 weeks from your formal complaint, or when you receive a final response letter from {company_name}, you can refer your case to the Financial Ombudsman Service (FOS) for free.",
      action_type: "info",
      action_config: {
        check_8_week_deadline: true,
        tip: "You have 6 months from the date of {company_name}'s final response letter to refer to FOS. The FOS can award up to £375,000 in compensation.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "fos-letter",
    },
    {
      step_id: "fos-letter",
      order: 7,
      title: "Draft Your FOS Referral Letter",
      description: "Prepare a structured complaint for the Financial Ombudsman Service covering the full chronology of your dispute.",
      action_type: "send_letter",
      action_config: {
        letter_type: "ombudsman_referral",
        auto_generate: true,
        prompt_context: "bank_charges_fos",
        tip: "The FOS adjudicator wants facts, not emotion. Focus on the regulatory breaches, the specific charges, and the dates of every step you took.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-fos",
    },
    {
      step_id: "escalate-fos",
      order: 8,
      title: "Submit to the Financial Ombudsman",
      description: "Submit your complaint to the FOS. The service is free and independent, and can order {company_name} to refund all charges plus compensation.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "Financial Ombudsman Service",
        escalation_url: "https://www.financial-ombudsman.org.uk",
        escalation_method: "Online complaint form, phone, or post",
        tip: "You can submit online at financial-ombudsman.org.uk. Attach your full case PDF and the FOS referral letter.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "resolve",
      order: 9,
      title: "Record the Outcome",
      description: "Record how your bank charges dispute was resolved.",
      action_type: "resolve",
      action_config: { trigger_outcome_form: true },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: null,
    },
  ],
};

const FAULTY_PRODUCT: JourneyTemplate = {
  id: "faulty-product",
  name: "Faulty Product Complaint",
  description: "Step-by-step guide to getting a refund, repair, or replacement under the Consumer Rights Act 2015.",
  category: "retail",
  estimated_duration_days: 56,
  steps: [
    {
      step_id: "gather-evidence",
      order: 1,
      title: "Gather Your Evidence",
      description: "Make sure you have everything you need before contacting {company_name}.",
      action_type: "checklist",
      action_config: {
        items: [
          "Find your receipt, order confirmation email, or bank statement showing the purchase",
          "Note the exact date of purchase and the price paid",
          "Describe the fault in detail — when it appeared and what it does",
          "Take photos or video of the fault",
          "Note any previous contact with {company_name} about this fault",
          "Keep the original packaging if possible",
        ],
        tip: "Your rights are against the retailer ({company_name}), not the manufacturer. Always contact the retailer first.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "purchase-timing",
    },
    {
      step_id: "purchase-timing",
      order: 2,
      title: "When Did You Buy It?",
      description: "Your rights under the Consumer Rights Act 2015 depend on how long ago you bought the product.",
      action_type: "branch",
      action_config: {
        question: "When did you purchase the product from {company_name}?",
        options: [
          {
            label: "Within the last 30 days — I want a full refund (short-term right to reject)",
            next_step: "reject-letter",
          },
          {
            label: "More than 30 days ago — I want a repair or replacement",
            next_step: "repair-letter",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "reject-letter",
    },
    {
      step_id: "reject-letter",
      order: 3,
      title: "Send Your Short-Term Right to Reject Letter",
      description: "Within 30 days of purchase you have an absolute right to reject a faulty product and get a full refund. {company_name} cannot insist on a repair or replacement first.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "faulty_product_reject",
        tip: "Section 22 of the Consumer Rights Act 2015 gives you an absolute short-term right to reject within 30 days. {company_name}'s return policy does not override the law.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "repair-letter",
      order: 3,
      title: "Send Your Repair or Replacement Request",
      description: "Request a repair or replacement under section 23 of the Consumer Rights Act 2015. {company_name} must carry this out within a reasonable time.",
      action_type: "send_letter",
      action_config: {
        letter_type: "initial_complaint",
        auto_generate: true,
        prompt_context: "faulty_product_repair",
        tip: "Within the first 6 months, the burden of proof is on {company_name} to show the goods were NOT faulty at delivery (Consumer Rights Act 2015, s.19(14)).",
      },
      completion_criteria: { type: "letter_sent", letter_type: "initial_complaint" },
      wait_after_days: 0,
      next_step: "wait-response-1",
    },
    {
      step_id: "wait-response-1",
      order: 4,
      title: "Wait for {company_name}'s Response",
      description: "{company_name} has 14 days to respond to your request.",
      action_type: "wait",
      action_config: {
        wait_message: "Waiting for {company_name} to respond to your faulty product complaint.",
        tip: "If {company_name} asks you to return the item, do so — but keep a copy of all correspondence and postage receipts.",
      },
      completion_criteria: { type: "days_passed", days: 14 },
      wait_after_days: 14,
      wait_message: "Waiting for {company_name} to respond (14 days)",
      next_step: "response-check-1",
    },
    {
      step_id: "response-check-1",
      order: 5,
      title: "How Did {company_name} Respond?",
      description: "Choose the option that best describes what happened.",
      action_type: "branch",
      action_config: {
        question: "What was {company_name}'s response?",
        options: [
          {
            label: "They agreed — I received a refund, repair, or replacement",
            next_step: "resolve",
          },
          {
            label: "They refused or offered an inadequate remedy",
            next_step: "followup-letter",
          },
          {
            label: "No response after 14+ days",
            next_step: "followup-letter",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "followup-letter",
    },
    {
      step_id: "followup-letter",
      order: 6,
      title: "Challenge Their Refusal",
      description: "Send a firmer follow-up letter. If they refused your short-term rejection, remind them that statute overrides their store policy. If a repair failed, you can now demand a price reduction or the final right to reject.",
      action_type: "send_letter",
      action_config: {
        letter_type: "follow_up",
        auto_generate: true,
        prompt_context: "faulty_product_followup_reject",
        tip: "Mention that you intend to pursue the matter through your credit card provider (Section 75 claim), through a chargeback, or through the County Court if the matter is not resolved within 14 days.",
      },
      completion_criteria: { type: "letter_sent", letter_type: "follow_up" },
      wait_after_days: 0,
      next_step: "payment-method-check",
    },
    {
      step_id: "payment-method-check",
      order: 7,
      title: "How Did You Pay?",
      description: "Your next escalation route depends on how you paid for the product.",
      action_type: "branch",
      action_config: {
        question: "How did you pay for the product from {company_name}?",
        options: [
          {
            label: "By credit card (item cost between £100 and £30,000) — Section 75 claim",
            next_step: "section75-letter",
          },
          {
            label: "By debit card, cash, buy-now-pay-later, or credit card under £100 — Letter Before Action",
            next_step: "lba-letter",
          },
        ],
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "lba-letter",
    },
    {
      step_id: "section75-letter",
      order: 8,
      title: "Send a Section 75 Claim to Your Credit Card Provider",
      description: "Under Section 75 of the Consumer Credit Act 1974, your credit card provider is jointly liable for {company_name}'s breach of contract. This is a powerful remedy.",
      action_type: "send_letter",
      action_config: {
        letter_type: "section_75_claim",
        auto_generate: true,
        prompt_context: "faulty_product_section75",
        tip: "This letter is addressed to your credit card provider, not to {company_name}. Attach all correspondence with {company_name} showing you attempted to resolve it directly first.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-fos-s75",
    },
    {
      step_id: "lba-letter",
      order: 8,
      title: "Send a Letter Before Action",
      description: "Send a formal Letter Before Action giving {company_name} 14 days to settle before you file a court claim. This is required before most court actions.",
      action_type: "send_letter",
      action_config: {
        letter_type: "letter_before_action",
        auto_generate: true,
        prompt_context: "faulty_product_lba",
        tip: "Many companies settle at this stage to avoid the cost and hassle of court. The County Court / Small Claims track (for claims under £10,000) is straightforward to use.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "escalate-court",
    },
    {
      step_id: "escalate-fos-s75",
      order: 9,
      title: "Escalate to the Financial Ombudsman (if Section 75 rejected)",
      description: "If your credit card provider rejects your Section 75 claim, you can refer it to the Financial Ombudsman Service for free.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "Financial Ombudsman Service",
        escalation_url: "https://www.financial-ombudsman.org.uk",
        escalation_method: "Online complaint form",
        tip: "If your credit card provider agrees the Section 75 claim, you may not need to go to FOS. Only escalate here if they reject the claim.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "escalate-court",
      order: 9,
      title: "File a Small Claims Court Claim",
      description: "File a Money Claim Online (MCOL) against {company_name}. The small claims track is designed for consumers and does not usually require a solicitor.",
      action_type: "escalate",
      action_config: {
        export_pdf: true,
        escalation_target: "County Court (Small Claims Track)",
        escalation_url: "https://www.gov.uk/make-court-claim-for-money",
        escalation_method: "Money Claim Online (MCOL)",
        tip: "Court fees are proportional to the claim amount (e.g. £35 for a £300 claim). You can usually recover these if you win. Most retailers settle before the hearing date.",
      },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: "resolve",
    },
    {
      step_id: "resolve",
      order: 10,
      title: "Record the Outcome",
      description: "Record how your faulty product complaint was resolved.",
      action_type: "resolve",
      action_config: { trigger_outcome_form: true },
      completion_criteria: { type: "manual" },
      wait_after_days: 0,
      next_step: null,
    },
  ],
};

export const JOURNEY_TEMPLATES: Record<string, JourneyTemplate> = {
  "energy-billing": ENERGY_BILLING,
  "broadband-speed": BROADBAND_SPEED,
  "flight-delay": FLIGHT_DELAY,
  "bank-charges": BANK_CHARGES,
  "faulty-product": FAULTY_PRODUCT,
};

export function getJourneyTemplate(id: string): JourneyTemplate | null {
  return JOURNEY_TEMPLATES[id] ?? null;
}

export function getJourneyStep(template: JourneyTemplate, stepId: string): import("@/types/journey").JourneyStep | null {
  return template.steps.find((s) => s.step_id === stepId) ?? null;
}

export function getFirstStep(template: JourneyTemplate): import("@/types/journey").JourneyStep {
  const sorted = [...template.steps].sort((a, b) => a.order - b.order);
  return sorted[0];
}

/** Returns the sequential list of steps in logical order (resolves branches by returning all unique steps). */
export function getOrderedSteps(template: JourneyTemplate): import("@/types/journey").JourneyStep[] {
  return [...template.steps].sort((a, b) => a.order - b.order);
}
