/**
 * Journey-specific AI letter prompt contexts.
 *
 * Each key matches the `prompt_context` field in a journey template's `action_config`.
 * The value is injected as `additionalInstructions` when the draft-letter API is called
 * from a journey step, layering on top of the standard letter prompt and case data.
 */
export const JOURNEY_LETTER_PROMPTS: Record<string, string> = {
  // ── Energy Billing ────────────────────────────────────────────────────────
  energy_billing_initial:
    "This is a formal complaint about an energy billing error — overcharging, estimated bills, direct debit increases without notice, or charges for energy not supplied. Reference the specific billing period and amounts from the case data. Cite the energy supplier's obligations under the Gas and Electricity Supply (Domestic) Standard Licence Conditions (particularly Standard Licence Condition 27 on billing accuracy and SLC 31 on payment methods). Also reference Ofgem's back-billing rule: suppliers cannot charge for energy used more than 12 months before the date the bill was issued, provided the customer did not prevent the supplier from obtaining accurate meter readings. Request an itemised bill showing how the disputed amount was calculated. Demand a refund of any overcharged amount and correction of the account within 14 days. Tone: professional and evidence-based, emphasising the specific figures.",

  energy_billing_followup:
    "This is a follow-up to a previous formal complaint about an energy billing error that has not been resolved. Reference the original complaint date and any response from the supplier from the case timeline. If the supplier acknowledged the complaint but failed to resolve it, note this. If they proposed a resolution that is unsatisfactory, explain why. Reiterate the amount in dispute and the specific billing errors. Invoke the Energy Ombudsman route: after 8 weeks from the formal complaint date (or upon receipt of a deadlock letter), the customer can escalate. State that escalation will follow if the matter is not resolved within 14 days. Tone: firmer than the initial complaint, demonstrating the pattern of failure to resolve.",

  energy_billing_ombudsman:
    "This is a referral to the Energy Ombudsman about an energy billing dispute. Summarise the complete complaint chronology: the nature of the billing error, the amount in dispute, the original complaint date, all communications with the supplier, any offers made, and why the matter remains unresolved. Reference the specific billing periods and amounts. State clearly that either 8 weeks have passed since the formal complaint or a deadlock letter was received. Set out the remedy sought: accurate billing, refund of overcharged amounts, and compensation for any distress or inconvenience caused. Tone: structured and factual, written for an independent adjudicator. Include all key dates from the case timeline.",

  // ── Broadband Speed ───────────────────────────────────────────────────────
  broadband_speed_initial:
    "This is a formal complaint about broadband speeds consistently falling below the contractual minimum guaranteed speed. Reference the customer's specific speed test evidence from the case data — include the guaranteed minimum speed from their contract and the actual speeds recorded. Cite Ofcom's Voluntary Code of Practice on Broadband Speeds if the provider is a signatory. Note the customer's right to a resolution or penalty-free exit under the code. Also reference that broadband services must be provided with reasonable care and skill under the Consumer Rights Act 2015, section 49. Request that the provider investigate and resolve the issue within 14 days, or confirm the customer's right to exit the contract. Tone: professional and evidence-based. Emphasise the factual speed test data.",

  broadband_speed_followup:
    "This is a follow-up to a previous complaint about broadband speeds. Reference the original complaint date and any actions taken by the provider (engineer visit, remote diagnostics) from the case timeline. Note that the issue remains unresolved and speeds are still below the guaranteed minimum. If an engineer visited but did not fix the issue, reference this. Cite the customer's right to exit under Ofcom's code and the provider's obligation under the Consumer Rights Act 2015. State that the customer will escalate to Alternative Dispute Resolution if the matter is not resolved within a further 14 days. Tone: firmer than the initial letter, emphasising the pattern of failure to resolve.",

  broadband_speed_adr:
    "This is a referral to an Alternative Dispute Resolution scheme (CISAS or Ombudsman Services: Communications) about a broadband speed complaint. Summarise the complete complaint chronology: original complaint date, speed test evidence, provider responses, engineer visits, follow-up complaints, and any offers made. Reference all broken promises from the case data. Clearly state: the contractual minimum guaranteed speed, the actual speeds consistently experienced, all steps taken to resolve the issue, and the outcome the customer is seeking (repair, exit without penalty, refund, compensation). Note that 8 weeks have passed since the formal complaint (or that a deadlock letter was received). Format for submission alongside the case PDF. Tone: factual, thorough, and structured for an adjudicator.",

  // ── Flight Delays ─────────────────────────────────────────────────────────
  flight_delay_initial:
    "This is a formal compensation claim for a flight delay or cancellation under UK Regulation EC 261/2004 (as retained by the Air Passenger Rights and Air Travel Organisers' Licensing (Amendment) (EU Exit) Regulations 2019). Include the flight number, date, route, booked departure and arrival times, and actual arrival time from the case data. Calculate and state the specific compensation amount based on the flight distance (under 1,500km = £220, 1,500-3,500km = £350, over 3,500km = £520). Reference the relevant regulation section. If the passenger had a connecting flight and the delay caused them to miss it, note this. Request payment within 14 days. Include the passenger's bank details placeholder for payment. Tone: formal and precise — this is a legal claim, not a general complaint.",

  flight_delay_followup:
    "This is a follow-up to a flight delay compensation claim that was either refused, partially offered (vouchers/reduced amount), or not responded to. If the airline cited extraordinary circumstances, challenge this — reference Huzar v Jet2.com Ltd [2014] EWCA Civ 791 and Corina van der Lans v KLM [2015] CJEU C-257/14 establishing that technical faults are not extraordinary circumstances. If vouchers were offered, state clearly that the passenger's legal entitlement is cash compensation and vouchers are not an acceptable substitute. Restate the compensation amount and the legal basis. Note that the passenger will escalate to ADR if the matter is not resolved within a further 14 days. Tone: firm and legally grounded.",

  flight_delay_adr:
    "This is a referral to an Alternative Dispute Resolution scheme (AviationADR/CEDR) for a flight delay compensation claim. Summarise the complete claim chronology: flight details, delay duration, original claim date, airline response (refusal reason or silence), follow-up sent, and current status. State the legal basis under UK261/EU261, the compensation amount claimed, and the distance band. If the airline cited extraordinary circumstances, explain why this is incorrect with reference to the specific circumstances and case law (Huzar v Jet2, Van der Lans v KLM). Include all evidence references. Note that 8 weeks have passed since the original claim. Tone: structured, factual, and thorough — written for an adjudicator.",

  // ── Bank Charges ──────────────────────────────────────────────────────────
  bank_charges_initial:
    "This is a formal complaint about bank charges that the customer believes are unfair or incorrect. Reference the specific charges from the case data — dates, amounts, and descriptions. State the total amount being disputed. If the charges are unauthorised overdraft fees, reference the FCA's overdraft pricing rules (since April 2020, banks must charge a simple annual interest rate with no fixed daily/monthly fees). If the charges result from a bank error, explain the error and its impact. If the charges are for a service not properly explained at point of sale, reference the Consumer Rights Act 2015 (unfair terms provisions). Request a full refund of the disputed charges within 14 days. Note that the customer will escalate to the Financial Ombudsman Service if the matter is not resolved within 8 weeks. Tone: professional and specific — focus on the factual details of each disputed charge.",

  bank_charges_followup:
    "This is a follow-up to a formal complaint about bank charges. Reference the original complaint date and any response from the bank. If the bank rejected the complaint, address their specific reasons and explain why the customer disagrees. If the bank offered a partial refund, explain why the full amount is owed. Restate the total amount disputed. Note that the customer intends to escalate to the Financial Ombudsman Service if the matter is not resolved. Reference the FCA's DISP rules requiring a final response within 8 weeks. Tone: firm but measured, building the case for escalation.",

  bank_charges_fos:
    "This is a referral to the Financial Ombudsman Service about disputed bank charges. Summarise the complaint chronology: the nature of the charges, when the formal complaint was made, the bank's response (if any), follow-up sent, and why the matter remains unresolved. State the total amount disputed and the specific charges. Reference the regulatory basis for the claim (FCA rules, Consumer Rights Act 2015 unfair terms, Payment Services Regulations 2017 as applicable). Include all broken promises from the case data. State clearly what outcome the customer is seeking (full refund, partial refund, compensation for distress and inconvenience). Note whether 8 weeks have passed or a final response letter was received. Important: remind the adjudicator that the customer has 6 months from the date of the bank's final response letter to refer to FOS. Tone: factual and structured for an adjudicator. Do not use emotional language — focus on the regulatory breaches and factual evidence.",

  // ── Faulty Products ───────────────────────────────────────────────────────
  faulty_product_reject:
    "This is a formal rejection of faulty goods under section 22 of the Consumer Rights Act 2015. The product was purchased less than 30 days ago. State the product name, purchase date, price, and order/receipt number from the case data. Describe the fault clearly. State that the customer is exercising their short-term right to reject the goods and requests a full refund within 14 days. Emphasise that within 30 days, the consumer has an absolute right to reject — the retailer cannot insist on a repair or replacement first. Note that this right overrides any store return policy. Tone: clear, assertive, and citing the specific statutory provisions.",

  faulty_product_repair:
    "This is a formal complaint about a faulty product requesting a repair or replacement under the Consumer Rights Act 2015 (sections 23-24). State the product name, purchase date, price, and fault description. Note that within the first 6 months, the burden of proof is on the retailer to show the goods were not faulty at delivery (section 19(14)). The consumer is requesting a repair or replacement as their chosen remedy. The retailer must carry this out within a reasonable time and without significant inconvenience. If the retailer does not provide an adequate remedy, the consumer will exercise their final right to reject under section 24. Tone: professional, citing specific CRA sections.",

  faulty_product_followup_reject:
    "This is a follow-up to a previous complaint about a faulty product where the retailer has refused or failed to provide a refund. Reference the original complaint date. If the retailer offered a repair instead of a refund for a product under 30 days old, state clearly that section 22 of the CRA gives the consumer an absolute short-term right to reject — the retailer's policy does not override statute. If this is a final right to reject after a failed repair, reference section 24 and note the failed repair attempt. State that the consumer will pursue the matter further (through their credit card provider, chargeback, or the courts) if the refund is not processed within 14 days. Tone: firm, legalistic, building towards escalation.",

  faulty_product_followup_repair:
    "This is a follow-up to a complaint where the retailer has failed to provide a timely repair or replacement. Reference the original complaint and the retailer's response (or lack thereof). Note that under section 23 of the CRA, repair or replacement must be done within a reasonable time and without significant inconvenience. If the retailer has exceeded a reasonable timeframe, the consumer is entitled to a price reduction or the final right to reject under section 24. State clearly what the consumer expects as a remedy and the deadline. Tone: firm, citing the statutory duty to provide a timely remedy.",

  faulty_product_section75:
    "This is a claim under section 75 of the Consumer Credit Act 1974 for a faulty product. The consumer purchased a product using a credit card. The product is faulty (describe fault from case data). The retailer has refused to provide a remedy under the Consumer Rights Act 2015 despite formal complaints (reference dates from case timeline). Under section 75, the credit card provider is jointly and severally liable for the retailer's breach of contract. The consumer requests a full refund of the purchase price. Include the product details, purchase date, retailer name, and a summary of the complaint history from the case data. Tone: formal, addressed to the financial institution.",

  faulty_product_fos_s75:
    "This is a referral to the Financial Ombudsman Service about a rejected Section 75 claim. The consumer purchased a faulty product, the retailer refused a remedy, and the credit card provider rejected the Section 75 claim. Summarise the full chronology from the case data: product purchase, fault discovery, retailer complaints (dates and responses), Section 75 claim to card provider, and the rejection. Reference section 75 of the Consumer Credit Act 1974 and the Consumer Rights Act 2015. State the amount being claimed and the outcome sought. Tone: structured for an FOS adjudicator.",

  faulty_product_lba:
    "This is a formal Letter Before Action (Pre-Action Protocol). It must be structured for use as a legal document and comply with the Practice Direction on Pre-Action Conduct. State clearly: the consumer's full name and address, the retailer's name and address, the amount claimed and how it is calculated (purchase price minus any fair deduction for use), the legal basis (breach of statutory rights under the Consumer Rights Act 2015 sections 9, 22, or 24 as applicable), a precise summary of the complaint history and the retailer's failure to provide a remedy (reference dates from case data), and a strict 14-day deadline to settle before court proceedings are issued at the County Court. Note that if the matter proceeds to court, the consumer will also claim court fees and statutory interest at 8% per annum. Tone: formal and legalistic — this is a legal document, not a complaint letter. Use plain language but leave no ambiguity about the intention to litigate.",

  // ── Dissolved company / fraudulent trading ────────────────────────────────
  dissolved_company_object_strikeoff:
    "This is a formal objection to the voluntary strike-off of a company, addressed to Companies House. The consumer has an outstanding contractual claim against the company. State: the company name and Companies House number, the nature of the contract and amount owed, the date of payment and the date of the First Gazette Notice (emphasising that the company took payment while the dissolution was pending, or that the consumer was not notified as required under s.1003 Companies Act 2006). Request that the strike-off be suspended. Cite s.1003 Companies Act 2006 (duty to notify creditors) and the consumer's right to object under the strike-off procedure. Address to: The Registrar of Companies, Companies House, Crown Way, Cardiff, CF14 3UZ. Tone: formal and factual.",

  dissolved_company_app_fraud:
    "This is a claim to the consumer's bank for reimbursement under the APP fraud reimbursement framework introduced by the Payment Systems Regulator in October 2024. The consumer paid by bank transfer to a company that was in the process of being dissolved (or had already been dissolved) at the time of payment. State: the consumer's account details (reference only, not full numbers), the payment amount, date and recipient, the company name and Companies House number, the date of the First Gazette Notice relative to the payment date, and why this constitutes APP fraud (the payment was induced by the fraudulent misrepresentation that the company was a valid trading entity when the directors knew it was being dissolved). Reference the Action Fraud crime reference number if available. Cite the PSR mandatory reimbursement requirement for APP fraud. Request full reimbursement of the amount paid. Tone: factual and firm, emphasising that this is a fraud claim not a commercial dispute.",

  dissolved_company_section75:
    "This is a Section 75 claim under the Consumer Credit Act 1974, addressed to the consumer's credit card provider. The consumer paid by credit card for goods or services from a company that was being dissolved or has been dissolved. State: the transaction amount and date, the credit card used (last four digits only), the company name and Companies House number, the nature of the goods or services contracted for, and the breach of contract (the company ceased to exist and cannot fulfil its obligations). Cite Section 75 of the Consumer Credit Act 1974 (joint and several liability of the credit card provider). Note that the cash price of the goods or services was between GBP 100 and GBP 30,000. Reference the Companies House filing showing the dissolution timeline. Request a full refund to the credit card. Tone: formal and clear.",

  dissolved_company_chargeback:
    "This is a request to the consumer's bank to initiate a chargeback for a debit card payment to a company that was being dissolved or has been dissolved. State: the transaction amount and date, the debit card used (last four digits only), the company name, and the reason for the chargeback (goods or services not received from a company that has ceased to exist). Note the chargeback reason code (typically 13.1 - Merchandise/Services Not Received under Visa, or 4855 under Mastercard). Emphasise that the 120-day chargeback window applies from the expected delivery date of the goods or services, not the payment date. Request the bank process the chargeback urgently given the company dissolution. Tone: factual and concise.",

  dissolved_company_fos_escalation:
    "This is a complaint to the Financial Ombudsman Service (FOS) about the consumer's bank or credit card provider refusing to reimburse them for a payment to a dissolved company. Summarise the complete timeline: the payment date and amount, the company dissolution dates (First and Final Gazette Notices), when the consumer discovered the dissolution, the claim made to the bank (APP fraud reimbursement, Section 75, or chargeback as applicable), the bank's response and reasons for refusal, and why the consumer believes the refusal is unfair. Reference the specific legal basis of the original claim. If an APP fraud claim, cite the PSR mandatory reimbursement requirement. If a Section 75 claim, cite the Consumer Credit Act 1974. Include the Action Fraud crime reference number and Trading Standards report reference if available. Note that 8 weeks have passed since the complaint to the bank (or that a final response letter has been received). Tone: structured, factual, and thorough - written for an adjudicator.",

  dissolved_company_lba_directors:
    "This is a Letter Before Action addressed to the director(s) of a dissolved company personally. The consumer paid the company for goods or services and the company was dissolved without fulfilling its obligations or refunding the consumer. State: the director names and home addresses (from Companies House filings), the consumer's name and address, the company name and Companies House number, the amount claimed and how it is calculated (original payment minus any partial recovery), the legal basis (breach of warranty of authority - the directors represented they were acting for a valid company, fraudulent misrepresentation, breach of duty under s.1003 Companies Act 2006 to notify creditors before applying for strike-off, and potential personal liability for fraudulent or wrongful trading under s.993 Companies Act 2006 and s.246ZB Insolvency Act 1986), a summary of the complaint history including Action Fraud report reference and Trading Standards complaint reference, and a 14-day deadline to pay the amount owed before court proceedings are issued. Note that if the matter proceeds to court, the consumer will also claim court fees, interest at the statutory rate under s.69 County Courts Act 1984, and may seek an order that the directors pay costs on an indemnity basis given the fraudulent conduct. Tone: formal and legalistic - this is a pre-action protocol letter.",
};

/**
 * Retrieve the journey-specific letter instructions for a given prompt context key.
 * Returns undefined if the key is not found (caller should proceed without additional context).
 */
export function getJourneyLetterPrompt(promptContext: string): string | undefined {
  return JOURNEY_LETTER_PROMPTS[promptContext];
}
