-- Seed canonical organisations (if missing) and published SEO rows with placeholder body copy.
-- Run scripts/generate-seo-content.ts to replace JSON sections with full researched content.

INSERT INTO public.organisations (name, category, ombudsman_name, escalation_wait_weeks)
SELECT v.name, v.cat::text, v.obm, v.ew
FROM (
  VALUES
    ('British Gas', 'energy', 'Energy Ombudsman', 8),
    ('E.ON', 'energy', 'Energy Ombudsman', 8),
    ('EDF', 'energy', 'Energy Ombudsman', 8),
    ('OVO Energy', 'energy', 'Energy Ombudsman', 8),
    ('Scottish Power', 'energy', 'Energy Ombudsman', 8),
    ('Octopus Energy', 'energy', 'Energy Ombudsman', 8),
    ('EE', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('TalkTalk', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('Vodafone', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('Virgin Media', 'broadband_phone', 'CISAS', 8),
    ('BT', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('Three', 'broadband_phone', 'CISAS', 8),
    ('O2', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('Sky', 'broadband_phone', 'Ombudsman Services: Communications', 8),
    ('Barclays', 'financial_services', 'Financial Ombudsman Service', 8),
    ('HSBC', 'financial_services', 'Financial Ombudsman Service', 8),
    ('Santander', 'financial_services', 'Financial Ombudsman Service', 8),
    ('Lloyds Bank', 'financial_services', 'Financial Ombudsman Service', 8),
    ('NatWest', 'financial_services', 'Financial Ombudsman Service', 8),
    ('Ryanair', 'transport', NULL, 8),
    ('easyJet', 'transport', NULL, 8),
    ('British Airways', 'transport', NULL, 8)
) AS v(name, cat, obm, ew)
WHERE NOT EXISTS (
  SELECT 1 FROM public.organisations o WHERE lower(trim(o.name)) = lower(trim(v.name))
);

-- Shared placeholder JSON fragments
-- your_rights / content: one starter card; escalation_steps / step_by_step: 3 steps; faq: 3 items; common_issues: 3 items

INSERT INTO public.seo_organisation_pages (
  organisation_id, slug, page_title, meta_description, sector, hero_heading, hero_subheading,
  your_rights, escalation_steps, faq_items, common_issues,
  ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days,
  related_guide_slugs, related_org_slugs, status, published_at
)
SELECT o.id, d.slug, d.page_title, d.meta_description, d.sector, d.hero_heading, d.hero_subheading,
  d.your_rights::jsonb, d.escalation_steps::jsonb, d.faq_items::jsonb, d.common_issues::jsonb,
  d.ombudsman_name, d.ombudsman_slug, d.regulator_name, d.primary_legislation, d.complaint_deadline_days::integer,
  d.related_guide_slugs, d.related_org_slugs, 'published', now()
FROM public.organisations o
JOIN (
  VALUES
    ('British Gas', 'british-gas', 'How to Complain to British Gas',
      'Step-by-step complaints against British Gas: your rights, deadlines, and escalation to the Energy Ombudsman. Draft a formal letter with TheyPromised.',
      'energy', $h$British Gas won't resolve your complaint?$h$, $s$Use UK energy rules to escalate fairly. TheyPromised helps you log evidence and draft a formal complaint in minutes.$s$,
      $json$[{"heading":"Fair complaints handling","body":"Energy suppliers must handle complaints under licence conditions and standards set by the regulator. This page will be expanded with firm-specific detail.","legislation_ref":"Gas Act 1986; Electricity Act 1989"}]$json$,
      $json$[{"step_number":1,"title":"Complain to British Gas","description":"Use their complaints process and keep a reference number.","deadline_days":null,"legislation_ref":"Ofgem Standards of Conduct"},{"step_number":2,"title":"Wait for a final response","description":"Typically up to eight weeks for an unresolved complaint before escalation.","deadline_days":56,"legislation_ref":"Energy company licence conditions"},{"step_number":3,"title":"Energy Ombudsman","description":"Free, independent dispute resolution if you remain unhappy.","deadline_days":null,"legislation_ref":"Alternative Dispute Resolution"}]$json$,
      $json$[{"question":"How long should British Gas take?","answer":"Many complaints should be resolved within eight weeks; complex cases can vary. Check your final response letter for the exact position."},{"question":"Can I go to the Energy Ombudsman?","answer":"Usually after eight weeks from your complaint or if you have a deadlock letter. Verify current rules on the Energy Ombudsman website."},{"question":"Is this legal advice?","answer":"No. This guide is for general information; verify deadlines with official sources."}]$json$,
      $json$[{"issue":"Billing and direct debits","description":"Estimated bills, balance disputes, and payment plans."},{"issue":"Smart meters","description":"Installation, readings, and communication faults."},{"issue":"Customer service delays","description":"Long waits and poor complaint handling."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989','Consumer Rights Act 2015']::text[], 56,
      ARRAY['energy-ombudsman-escalation','energy-billing-disputes']::text[],
      ARRAY['edf','eon','ovo-energy','octopus-energy','scottish-power']::text[]),
    ('E.ON', 'eon', 'How to Complain to E.ON',
      'Complain to E.ON with clear steps, regulator context, and escalation options including the Energy Ombudsman.',
      'energy', $h$Issues with E.ON billing or service?$h$, $s$Document every contact and escalate using the same protections that apply across licensed energy suppliers.$s$,
      $json$[{"heading":"Licensed supplier obligations","body":"E.ON must meet standards for complaints and vulnerable customers under licence and regulatory rules.","legislation_ref":"Gas Act 1986; Electricity Act 1989"}]$json$,
      $json$[{"step_number":1,"title":"Formal complaint to E.ON","description":"Raise via phone, webform, or post and retain evidence.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week review","description":"If still unresolved, note the date for ombudsman eligibility.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Energy Ombudsman","description":"Independent resolution for eligible complaints.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Can I switch while complaining?","answer":"You can usually switch; outstanding balances may still apply. Check E.ON and Ofgem guidance."},{"question":"What if my supply is at risk?","answer":"Contact Citizens Advice for urgent vulnerability or disconnection issues."},{"question":"Do I pay for the ombudsman?","answer":"The Energy Ombudsman service is free to consumers."}]$json$,
      $json$[{"issue":"Tariff confusion","description":"Fixed vs variable charges and exit fees."},{"issue":"Meter problems","description":"Faulty or inaccessible meters."},{"issue":"Back-billing","description":"Large catch-up bills and back-billing rules."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989']::text[], 56,
      ARRAY['energy-ombudsman-escalation']::text[],
      ARRAY['british-gas','edf','ovo-energy','octopus-energy','scottish-power']::text[]),
    ('EDF', 'edf', 'How to Complain to EDF',
      'EDF complaints: your rights, typical issues, and how to escalate beyond the supplier when deadlines are missed.',
      'energy', $h$EDF not fixing your problem?$h$, $s$Follow the regulated path from internal complaint to the Energy Ombudsman where appropriate.$s$,
      $json$[{"heading":"Consumer protections","body":"Domestic energy complaints are governed by licence conditions and consumer law.","legislation_ref":"Consumer Rights Act 2015"}]$json$,
      $json$[{"step_number":1,"title":"EDF complaints team","description":"Log the issue formally and request a written outcome.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Track the eight-week window","description":"Note when you can escalate if there is no fair resolution.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Energy Ombudsman","description":"Escalate eligible complaints for a binding decision.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"What evidence helps?","answer":"Bills, emails, chat transcripts, and call notes with dates and adviser names."},{"question":"Can I claim compensation?","answer":"The ombudsman can award compensation where appropriate; outcomes depend on facts."},{"question":"Where do I read official rules?","answer":"Use Ofgem and the Energy Ombudsman for the latest process details."}]$json$,
      $json$[{"issue":"Nuclear levy or tariff lines on bills","description":"Questions about charges and plan terms."},{"issue":"Smart meter appointments","description":"Missed or rearranged appointments."},{"issue":"Complaint handling delays","description":"Slow responses or unclear outcomes."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989']::text[], 56,
      ARRAY['energy-ombudsman-escalation','energy-billing-disputes']::text[],
      ARRAY['british-gas','eon','ovo-energy','octopus-energy','scottish-power']::text[]),
    ('OVO Energy', 'ovo-energy', 'How to Complain to OVO Energy',
      'OVO Energy complaints guide: deadlines, ombudsman escalation, and how to keep an evidence trail.',
      'energy', $h$OVO Energy complaint stuck?$h$, $s$Licensed suppliers must treat complaints fairly; here is the standard UK escalation route.$s$,
      $json$[{"heading":"Standards of conduct","body":"Suppliers must meet Ofgem-backed standards including clear complaints handling.","legislation_ref":"Ofgem Standards of Conduct"}]$json$,
      $json$[{"step_number":1,"title":"OVO complaint","description":"Use OVO channels and keep references.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Request a clear deadlock or final position if needed.","deadline_days":null,"legislation_ref":null},{"step_number":3,"title":"Energy Ombudsman","description":"Escalate within scheme time limits.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"What is a deadlock letter?","answer":"A letter saying the supplier will not change its position — often used to escalate sooner."}]$json$,
      $json$[{"issue":"Pay monthly reviews","description":"Direct debit changes and payment plans."},{"issue":"Switching blocks","description":"Objections or delays when moving supplier."},{"issue":"Customer service","description":"Repeat contacts without resolution."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989']::text[], 56,
      ARRAY['energy-ombudsman-escalation']::text[],
      ARRAY['british-gas','edf','eon','octopus-energy','scottish-power']::text[]),
    ('Scottish Power', 'scottish-power', 'How to Complain to Scottish Power',
      'Scottish Power complaints: regulator context, typical disputes, and Energy Ombudsman escalation.',
      'energy', $h$Scottish Power complaint not sorted?$h$, $s$Use the same statutory framework as other large domestic suppliers.$s$,
      $json$[{"heading":"Energy supply complaints","body":"Complaints about supply, billing, and service are covered by energy licensing and consumer law.","legislation_ref":"Electricity Act 1989"}]$json$,
      $json$[{"step_number":1,"title":"Scottish Power complaints","description":"Raise formally and chase in writing.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week checkpoint","description":"Assess ombudsman eligibility if unresolved.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Energy Ombudsman","description":"Independent review for eligible cases.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Is there a time limit for the ombudsman?","answer":"Yes — check the Energy Ombudsman website for current limits from your final response or eight-week date."}]$json$,
      $json$[{"issue":"Billing disputes","description":"Incorrect charges or estimates."},{"issue":"Prepayment meters","description":"Token, key, or smart PAYG faults."},{"issue":"Warm home discount","description":"Eligibility and administration issues."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989']::text[], 56,
      ARRAY['energy-ombudsman-escalation']::text[],
      ARRAY['british-gas','edf','eon','ovo-energy','octopus-energy']::text[]),
    ('Octopus Energy', 'octopus-energy', 'How to Complain to Octopus Energy',
      'Octopus Energy complaints: how to escalate fairly and when the Energy Ombudsman can step in.',
      'energy', $h$Octopus Energy not responding fairly?$h$, $s$Keep a timeline of contacts and use the regulated complaints path.$s$,
      $json$[{"heading":"Regulatory framework","body":"Octopus, like all domestic suppliers, must meet licence complaints standards.","legislation_ref":"Gas Act 1986"}]$json$,
      $json$[{"step_number":1,"title":"Octopus complaints","description":"Use official routes and save confirmations.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Assess resolution","description":"If unhappy after the allowed period, prepare to escalate.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Energy Ombudsman","description":"Free ADR for eligible complaints.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Does Octopus publish complaint data?","answer":"Ofgem publishes broad industry data; use it as context, not a prediction of your outcome."}]$json$,
      $json$[{"issue":"Agile / smart tariffs","description":"Complex pricing and display issues."},{"issue":"Referrals and credit balances","description":"Final bills and refunds."},{"issue":"Smart meter communications","description":"Connectivity and billing impacts."}]$json$,
      'Energy Ombudsman', 'energy-ombudsman-escalation', 'Ofgem',
      ARRAY['Gas Act 1986','Electricity Act 1989']::text[], 56,
      ARRAY['energy-ombudsman-escalation']::text[],
      ARRAY['british-gas','edf','eon','ovo-energy','scottish-power']::text[])
) AS d(org_name, slug, page_title, meta_description, sector, hero_heading, hero_subheading, your_rights, escalation_steps, faq_items, common_issues, ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days, related_guide_slugs, related_org_slugs)
  ON lower(trim(o.name)) = lower(trim(d.org_name))
ON CONFLICT (slug) DO NOTHING;

-- Telecoms (abbreviated placeholders — expand via generator script)
INSERT INTO public.seo_organisation_pages (
  organisation_id, slug, page_title, meta_description, sector, hero_heading, hero_subheading,
  your_rights, escalation_steps, faq_items, common_issues,
  ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days,
  related_guide_slugs, related_org_slugs, status, published_at
)
SELECT o.id, d.slug, d.page_title, d.meta_description, d.sector, d.hero_heading, d.hero_subheading,
  d.your_rights::jsonb, d.escalation_steps::jsonb, d.faq_items::jsonb, d.common_issues::jsonb,
  d.ombudsman_name, d.ombudsman_slug, d.regulator_name, d.primary_legislation, d.complaint_deadline_days::integer,
  d.related_guide_slugs, d.related_org_slugs, 'published', now()
FROM public.organisations o
JOIN (
  VALUES
    ('EE', 'ee', 'How to Complain to EE', 'EE complaints: Ofcom framework, ADR schemes, and escalation routes for mobile and broadband.', 'telecoms',
      $h$EE complaint going nowhere?$h$, $s$Telecoms providers must offer access to approved ADR when complaints deadlock.$s$,
      $json$[{"heading":"Communications providers","body":"EE must comply with Ofcom general conditions including complaints handling.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"EE complaints","description":"Use EE process and keep records.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week point","description":"If unresolved, you can usually refer to ADR.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Approved ADR","description":"Ombudsman Services: Communications or CISAS depending on provider rules.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Which ombudsman applies?","answer":"Depends on EE’s membership — confirm on Ofcom’s ADR pages and EE’s final response."}]$json$,
      $json$[{"issue":"Billing","description":"Unexpected charges and plan disputes."},{"issue":"Coverage","description":"Service quality complaints."},{"issue":"Retention offers","description":"Disputes after contract changes."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint','broadband-speed-complaints']::text[],
      ARRAY['vodafone','o2','three','bt','talktalk','sky','virgin-media']::text[]),
    ('TalkTalk', 'talktalk', 'How to Complain to TalkTalk', 'TalkTalk broadband and phone complaints: ADR, Ofcom rules, and practical steps.', 'telecoms',
      $h$TalkTalk not fixing your broadband?$h$, $s$Keep speed tests and engineer notes as evidence.$s$,
      $json$[{"heading":"Ofcom protections","body":"Providers must have complaints codes and ADR access.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"TalkTalk complaint","description":"Formal complaint with reference.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Deadlock or eight weeks","description":"Check eligibility for ADR.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"ADR scheme","description":"Escalate via the relevant ombudsman.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Can I leave early?","answer":"Depends on contract and fault — review Ofcom guidance on early exit for persistent issues."}]$json$,
      $json$[{"issue":"Speed faults","description":"Below-advertised speeds."},{"issue":"Outages","description":"Repeated loss of service."},{"issue":"Billing","description":"Incorrect charges."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint','broadband-speed-complaints']::text[],
      ARRAY['ee','bt','sky','virgin-media']::text[]),
    ('Vodafone', 'vodafone', 'How to Complain to Vodafone', 'Vodafone UK complaints: mobile and broadband escalation under Ofcom rules.', 'telecoms',
      $h$Vodafone dispute unresolved?$h$, $s$ADR is available when process deadlines are met.$s$,
      $json$[{"heading":"General conditions","body":"Vodafone must meet Ofcom conditions on complaints and ADR.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"Vodafone complaint","description":"Use official channels.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Wait for final response","description":"Typically eight weeks for deadlocked complaints.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"ADR","description":"Refer to the approved scheme.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Is CISAS or OS my route?","answer":"Check Vodafone’s complaints code and final response letter for the correct scheme."}]$json$,
      $json$[{"issue":"Roaming charges","description":"Unexpected bills abroad."},{"issue":"Upgrade disputes","description":"Handset and plan changes."},{"issue":"Credit file markers","description":"Default or missed payment disputes."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint']::text[],
      ARRAY['ee','o2','three']::text[]),
    ('Virgin Media', 'virgin-media', 'How to Complain to Virgin Media', 'Virgin Media complaints: broadband/TV/phone and CISAS escalation where eligible.', 'telecoms',
      $h$Virgin Media service problems?$h$, $s$Document outages and engineer visits carefully.$s$,
      $json$[{"heading":"CISAS route","body":"Virgin Media typically uses CISAS for eligible deadlocked complaints.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"Virgin Media complaint","description":"Raise formally.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week review","description":"Assess ADR eligibility.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"CISAS","description":"Independent adjudication for eligible disputes.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"What counts as a deadlock?","answer":"A clear statement that the provider’s position is final, or eight weeks without resolution."}]$json$,
      $json$[{"issue":"Speed and latency","description":"Cable/FTTP performance issues."},{"issue":"Installation","description":"Missed appointments and damage."},{"issue":"Retention pricing","description":"Discount and contract disputes."}]$json$,
      'CISAS', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint','broadband-speed-complaints']::text[],
      ARRAY['bt','sky','talktalk']::text[]),
    ('BT', 'bt', 'How to Complain to BT', 'BT complaints: broadband, phone, and EE-branded services — Ofcom rules and ADR.', 'telecoms',
      $h$BT complaint unresolved?$h$, $s$BT must provide access to an approved ADR scheme.$s$,
      $json$[{"heading":"BT as communications provider","body":"Complaints handling is regulated under general conditions.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"BT complaint","description":"Use BT’s process.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week rule of thumb","description":"Check your final response for ADR rights.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"ADR","description":"Refer to the scheme named in your correspondence.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"BT and EE combined accounts?","answer":"Follow the entity named on your bill and the complaints letter."}]$json$,
      $json$[{"issue":"Openreach appointments","description":"Engineer no-shows and delays."},{"issue":"Digital voice","description":"Switchover and reliability issues."},{"issue":"Billing bundles","description":"Discount stacking errors."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint','broadband-speed-complaints']::text[],
      ARRAY['ee','talktalk']::text[]),
    ('Three', 'three', 'How to Complain to Three', 'Three UK complaints: mobile service disputes and CISAS escalation.', 'telecoms',
      $h$Three not helping?$h$, $s$Keep proof of poor coverage claims and billing.$s$,
      $json$[{"heading":"Ofcom framework","body":"Three must comply with complaints and ADR requirements.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"Three complaint","description":"Formal complaint first.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Request deadlock if stuck.","deadline_days":null,"legislation_ref":null},{"step_number":3,"title":"CISAS","description":"Where Three directs eligible cases.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Pay-as-you-go issues?","answer":"Same complaints standards generally apply; keep top-up and usage records."}]$json$,
      $json$[{"issue":"5G/4G speeds","description":"Performance vs marketing."},{"issue":"Roaming","description":"EU and worldwide add-ons."},{"issue":"Credit checks","description":"Contract refusal disputes."}]$json$,
      'CISAS', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint']::text[],
      ARRAY['ee','vodafone','o2']::text[]),
    ('O2', 'o2', 'How to Complain to O2', 'O2 complaints: mobile plans, billing, and ombudsman escalation routes.', 'telecoms',
      $h$O2 complaint stuck?$h$, $s$Use written complaints to lock in dates for ADR.$s$,
      $json$[{"heading":"Regulated complaints","body":"O2 must meet Ofcom general conditions.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"O2 complaint","description":"Use O2 channels.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight weeks","description":"Typical ADR threshold if unresolved.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"ADR","description":"Scheme named in final correspondence.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Virgin Media O2 bundles?","answer":"Check which brand issued the final response for escalation."}]$json$,
      $json$[{"issue":"Custom plans","description":"Discount expiry disputes."},{"issue":"Device plans","description":"Insurance and repair rows."},{"issue":"PAC/STAC delays","description":"Porting problems."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint']::text[],
      ARRAY['vodafone','three','ee']::text[]),
    ('Sky', 'sky', 'How to Complain to Sky', 'Sky broadband and TV complaints: Ofcom rules and ADR for deadlocked disputes.', 'telecoms',
      $h$Sky billing or service dispute?$h$, $s$Keep contract documents and message logs.$s$,
      $json$[{"heading":"Sky as provider","body":"Sky must offer complaints handling and ADR access like other major providers.","legislation_ref":"Communications Act 2003"}]$json$,
      $json$[{"step_number":1,"title":"Sky complaint","description":"Formal complaint with reference.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Eight-week assessment","description":"ADR if still unresolved.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"ADR","description":"Follow Sky’s final response.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Sky Glass / Stream issues?","answer":"Treat as regulated complaints where services fall under general conditions."}]$json$,
      $json$[{"issue":"Price rises","description":"In-contract increase disputes."},{"issue":"Broadband speed","description":"Guaranteed speed codes where applicable."},{"issue":"TV packs","description":"Channel removals and billing."}]$json$,
      'Ombudsman Services: Communications', 'ofcom-complaint', 'Ofcom',
      ARRAY['Communications Act 2003']::text[], 56,
      ARRAY['ofcom-complaint','broadband-speed-complaints']::text[],
      ARRAY['virgin-media','bt','talktalk']::text[])
) AS d(org_name, slug, page_title, meta_description, sector, hero_heading, hero_subheading, your_rights, escalation_steps, faq_items, common_issues, ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days, related_guide_slugs, related_org_slugs)
  ON lower(trim(o.name)) = lower(trim(d.org_name))
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.seo_organisation_pages (
  organisation_id, slug, page_title, meta_description, sector, hero_heading, hero_subheading,
  your_rights, escalation_steps, faq_items, common_issues,
  ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days,
  related_guide_slugs, related_org_slugs, status, published_at
)
SELECT o.id, d.slug, d.page_title, d.meta_description, d.sector, d.hero_heading, d.hero_subheading,
  d.your_rights::jsonb, d.escalation_steps::jsonb, d.faq_items::jsonb, d.common_issues::jsonb,
  d.ombudsman_name, d.ombudsman_slug, d.regulator_name, d.primary_legislation, d.complaint_deadline_days::integer,
  d.related_guide_slugs, d.related_org_slugs, 'published', now()
FROM public.organisations o
JOIN (
  VALUES
    ('Barclays', 'barclays', 'How to Complain to Barclays', 'Barclays complaints: FCA DISP rules, eight-week final response, and the Financial Ombudsman Service.', 'financial',
      $h$Barclays complaint unresolved?$h$, $s$Banks must follow DISP for eligible complaints about regulated activities.$s$,
      $json$[{"heading":"FCA DISP","body":"Barclays must handle complaints fairly and give final responses within defined timeframes for eligible complaints.","legislation_ref":"FCA Handbook DISP"}]$json$,
      $json$[{"step_number":1,"title":"Barclays complaint","description":"Use branch, app, or written complaints.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response letter","description":"Barclays should explain outcome and FOS rights.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"Financial Ombudsman","description":"Refer within FOS time limits if eligible.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Is every bank issue FOS-eligible?","answer":"No — eligibility depends on regulated activity and complainant status; read Barclays’ final response."}]$json$,
      $json$[{"issue":"Fraud and scams","description":"Authorised push payment and card disputes."},{"issue":"Mortgage administration","description":"Fees, arrears, and forbearance."},{"issue":"Packaged accounts","description":"Insurance and fee disputes."}]$json$,
      'Financial Ombudsman Service', 'financial-ombudsman-complaint', 'FCA',
      ARRAY['Financial Services and Markets Act 2000','Consumer Credit Act 1974','FCA Handbook (DISP)']::text[], 56,
      ARRAY['financial-ombudsman-complaint','chargeback-guide','section-75-claim']::text[],
      ARRAY['hsbc','lloyds','natwest','santander']::text[]),
    ('HSBC', 'hsbc', 'How to Complain to HSBC', 'HSBC UK complaints: DISP timelines, credit card Section 75 context, and FOS referral.', 'financial',
      $h$HSBC not treating your complaint fairly?$h$, $s$Keep account statements and secure messages as evidence.$s$,
      $json$[{"heading":"Regulated complaints","body":"HSBC UK Bank plc handles many complaints under DISP.","legislation_ref":"FCA Handbook DISP"}]$json$,
      $json$[{"step_number":1,"title":"HSBC complaint","description":"Use HSBC process.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Eight weeks for many banking complaints unless extended with notice.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"FOS","description":"Refer if eligible and within time limits.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Premier vs standard banking?","answer":"DISP still applies to eligible complaints; service tier does not remove regulatory duties."}]$json$,
      $json$[{"issue":"Mortgage offers","description":"Delays and valuation disputes."},{"issue":"Business vs personal","description":"Eligibility can differ — check final response."},{"issue":"International transfers","description":"Fees and execution disputes."}]$json$,
      'Financial Ombudsman Service', 'financial-ombudsman-complaint', 'FCA',
      ARRAY['FCA Handbook (DISP)','Consumer Credit Act 1974']::text[], 56,
      ARRAY['financial-ombudsman-complaint','section-75-claim']::text[],
      ARRAY['barclays','lloyds','natwest','santander']::text[]),
    ('Santander', 'santander', 'How to Complain to Santander', 'Santander complaints: banking and lending DISP process and FOS escalation.', 'financial',
      $h$Santander complaint delayed?$h$, $s$Request a written final response to start FOS time limits.$s$,
      $json$[{"heading":"DISP requirements","body":"Santander must acknowledge and resolve complaints within regulatory timeframes.","legislation_ref":"FCA Handbook DISP"}]$json$,
      $json$[{"step_number":1,"title":"Santander complaint","description":"Formal complaint.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Check FOS rights section.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"FOS","description":"Refer if appropriate.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"123 account disputes?","answer":"Treat as standard eligible complaints where they concern regulated banking services."}]$json$,
      $json$[{"issue":"Mortgage SVR","description":"Rate change disputes."},{"issue":"Car finance","description":"PCP and HP complaints."},{"issue":"Branch closures","description":"Access and communication issues."}]$json$,
      'Financial Ombudsman Service', 'financial-ombudsman-complaint', 'FCA',
      ARRAY['FCA Handbook (DISP)','Consumer Credit Act 1974']::text[], 56,
      ARRAY['financial-ombudsman-complaint']::text[],
      ARRAY['barclays','hsbc','lloyds','natwest']::text[]),
    ('Lloyds Bank', 'lloyds', 'How to Complain to Lloyds Bank', 'Lloyds Bank complaints: DISP, credit card disputes, and Financial Ombudsman referral.', 'financial',
      $h$Lloyds Bank complaint stuck?$h$, $s$Section 75 may apply to certain card purchases — see our separate guide.$s$,
      $json$[{"heading":"Banking complaints","body":"Lloyds must comply with DISP for eligible complaints.","legislation_ref":"FCA Handbook DISP"}]$json$,
      $json$[{"step_number":1,"title":"Lloyds complaint","description":"Use official channels.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Eight-week benchmark for many complaints.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"FOS","description":"Escalate within published limits.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Halifax / BM / LBG brands?","answer":"Complaints are handled by the relevant legal entity — check your final response letterhead."}]$json$,
      $json$[{"issue":"Overdraft charges","description":"Historical and current fee disputes."},{"issue":"Scam reimbursement","description":"APP fraud decisions."},{"issue":"Credit file","description":"Marker disputes."}]$json$,
      'Financial Ombudsman Service', 'financial-ombudsman-complaint', 'FCA',
      ARRAY['FCA Handbook (DISP)','Consumer Credit Act 1974']::text[], 56,
      ARRAY['financial-ombudsman-complaint','section-75-claim','chargeback-guide']::text[],
      ARRAY['barclays','hsbc','natwest','santander']::text[]),
    ('NatWest', 'natwest', 'How to Complain to NatWest', 'NatWest complaints: RBS Group brands, DISP, and FOS rights.', 'financial',
      $h$NatWest complaint unresolved?$h$, $s$Ulster Bank / NatWest routing depends on the entity on your account.$s$,
      $json$[{"heading":"DISP","body":"Eligible complaints receive final responses with FOS information.","legislation_ref":"FCA Handbook DISP"}]$json$,
      $json$[{"step_number":1,"title":"NatWest complaint","description":"Formal complaint.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Final response","description":"Review outcome and next steps.","deadline_days":56,"legislation_ref":null},{"step_number":3,"title":"FOS","description":"Refer if eligible.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Royal Bank of Scotland accounts?","answer":"Use the brand named on your documentation for the correct complaints address."}]$json$,
      $json$[{"issue":"Business banking","description":"Eligibility nuances for micro-enterprises."},{"issue":"Loan decisions","description":"Affordability and communication."},{"issue":"Digital banking","description":"App outages and payment failures."}]$json$,
      'Financial Ombudsman Service', 'financial-ombudsman-complaint', 'FCA',
      ARRAY['FCA Handbook (DISP)','Consumer Credit Act 1974']::text[], 56,
      ARRAY['financial-ombudsman-complaint']::text[],
      ARRAY['barclays','hsbc','lloyds','santander']::text[])
) AS d(org_name, slug, page_title, meta_description, sector, hero_heading, hero_subheading, your_rights, escalation_steps, faq_items, common_issues, ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days, related_guide_slugs, related_org_slugs)
  ON lower(trim(o.name)) = lower(trim(d.org_name))
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.seo_organisation_pages (
  organisation_id, slug, page_title, meta_description, sector, hero_heading, hero_subheading,
  your_rights, escalation_steps, faq_items, common_issues,
  ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days,
  related_guide_slugs, related_org_slugs, status, published_at
)
SELECT o.id, d.slug, d.page_title, d.meta_description, d.sector, d.hero_heading, d.hero_subheading,
  d.your_rights::jsonb, d.escalation_steps::jsonb, d.faq_items::jsonb, d.common_issues::jsonb,
  d.ombudsman_name, d.ombudsman_slug, d.regulator_name, d.primary_legislation, d.complaint_deadline_days::integer,
  d.related_guide_slugs, d.related_org_slugs, 'published', now()
FROM public.organisations o
JOIN (
  VALUES
    ('Ryanair', 'ryanair', 'How to Complain to Ryanair', 'Ryanair complaints: UK261 flight disruption rights and Consumer Rights Act context.', 'travel',
      $h$Ryanair flight problem?$h$, $s$Keep booking references and airport timestamps for evidence.$s$,
      $json$[{"heading":"UK261 rights","body":"Many flight disruption claims sit under retained EU261/UK261 rules for qualifying flights.","legislation_ref":"Retained EU Regulation 261/2004 (UK261)"}]$json$,
      $json$[{"step_number":1,"title":"Ryanair complaint","description":"Use Ryanair’s claims and complaints routes.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"ADR / court letter","description":"If deadlocked, consider ADR where offered or court for small claims in some cases.","deadline_days":null,"legislation_ref":null},{"step_number":3,"title":"Document everything","description":"Boarding passes, delay notices, and emails."}]$json$,
      $json$[{"question":"Is every delay compensatable?","answer":"UK261 has specific tests including distance and delay length — verify for your itinerary."}]$json$,
      $json$[{"issue":"Denied boarding","description":"Overbooking rows."},{"issue":"Cancelled flights","description":"Re-routing and refunds."},{"issue":"Baggage","description":"Delayed or damaged luggage."}]$json$,
      NULL, 'flight-delay-compensation', 'CAA',
      ARRAY['UK261 (retained EU Regulation 261/2004)','Consumer Rights Act 2015']::text[], NULL,
      ARRAY['flight-delay-compensation','consumer-rights-act-2015']::text[],
      ARRAY['easyjet','british-airways']::text[]),
    ('easyJet', 'easyjet', 'How to Complain to easyJet', 'easyJet complaints: disruption compensation basics and escalation options.', 'travel',
      $h$easyJet cancelled or delayed your flight?$h$, $s$Check UK261 criteria before accepting vouchers only.$s$,
      $json$[{"heading":"Air passenger rights","body":"UK261 may provide compensation, re-routing, or care in qualifying cases.","legislation_ref":"UK261"}]$json$,
      $json$[{"step_number":1,"title":"easyJet complaint","description":"Submit via easyJet channels.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Written outcome","description":"Challenge unclear refusals with evidence.","deadline_days":null,"legislation_ref":null},{"step_number":3,"title":"ADR or court","description":"Where offered and proportionate.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Extraordinary circumstances?","answer":"Carriers sometimes refuse claims — verify CAA/EU261 guidance on what counts."}]$json$,
      $json$[{"issue":"Long delays on the tarmac","description":"Care and communication failures."},{"issue":"Downgrades","description":"Class change refunds."},{"issue":"Refunds vs vouchers","description":"Cash refund rights in many cancellation scenarios."}]$json$,
      NULL, 'flight-delay-compensation', 'CAA',
      ARRAY['UK261','Consumer Rights Act 2015']::text[], NULL,
      ARRAY['flight-delay-compensation']::text[],
      ARRAY['ryanair','british-airways']::text[]),
    ('British Airways', 'british-airways', 'How to Complain to British Airways', 'British Airways complaints: UK261, Montreal Convention baggage limits, and Consumer Rights Act.', 'travel',
      $h$BA complaint unresolved?$h$, $s$Long-haul and short-haul rules differ under UK261.$s$,
      $json$[{"heading":"Layered rights","body":"Flight disruption, baggage, and service complaints may involve different legal bases.","legislation_ref":"Montreal Convention; UK261"}]$json$,
      $json$[{"step_number":1,"title":"BA complaint","description":"Use BA customer relations.","deadline_days":null,"legislation_ref":null},{"step_number":2,"title":"Escalate in writing","description":"Clear chronology and desired outcome.","deadline_days":null,"legislation_ref":null},{"step_number":3,"title":"ADR / court","description":"Consider CEDR or court routes where appropriate.","deadline_days":null,"legislation_ref":null}]$json$,
      $json$[{"question":"Avios and Executive Club?","answer":"Separate terms may apply — identify whether the complaint is about the flight or the loyalty scheme."}]$json$,
      $json$[{"issue":"Downgrades","description":"Involuntary cabin changes."},{"issue":"Connections","description":"Missed connections on single tickets."},{"issue":"Baggage","description":"Delayed bags and expenses."}]$json$,
      NULL, 'flight-delay-compensation', 'CAA',
      ARRAY['UK261','Consumer Rights Act 2015','Montreal Convention']::text[], NULL,
      ARRAY['flight-delay-compensation','consumer-rights-act-2015']::text[],
      ARRAY['ryanair','easyjet']::text[])
) AS d(org_name, slug, page_title, meta_description, sector, hero_heading, hero_subheading, your_rights, escalation_steps, faq_items, common_issues, ombudsman_name, ombudsman_slug, regulator_name, primary_legislation, complaint_deadline_days, related_guide_slugs, related_org_slugs)
  ON lower(trim(o.name)) = lower(trim(d.org_name))
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.seo_guide_pages (
  slug, page_title, meta_description, category, sector, hero_heading, hero_subheading,
  introduction, content_sections, eligibility_criteria, step_by_step, faq_items,
  primary_legislation, key_deadlines, related_org_slugs, related_guide_slugs, status, published_at
) VALUES
(
  'energy-ombudsman-escalation',
  'How to Escalate to the Energy Ombudsman',
  'When and how to escalate energy complaints to the Energy Ombudsman after eight weeks or a deadlock letter.',
  'ombudsman', 'energy',
  $gh$Escalate an unresolved energy complaint$gh$,
  $gs$Free, independent dispute resolution for many domestic energy complaints.$gs$,
  $gi$If your supplier has not resolved your complaint within the required timeframe, or has issued a deadlock letter, you may be able to refer the matter to the Energy Ombudsman.$gi$,
  $json$[{"heading":"Eligibility basics","body":"Eligibility depends on your complaint type, supplier licence, and whether internal processes have completed. Always confirm on the Energy Ombudsman website.","legislation_ref":"Energy company licence conditions"}]$json$::jsonb,
  $json$[{"criterion":"Domestic consumer","description":"Most schemes focus on domestic customers."},{"criterion":"Time limits","description":"Refer within the ombudsman’s published limits."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Complete supplier process","description":"Raise a formal complaint and keep references.","tip":"Write down dates and adviser names."},{"step_number":2,"title":"Eight weeks or deadlock","description":"Check if you can refer now.","tip":"A deadlock letter can shorten the wait."},{"step_number":3,"title":"Submit to ombudsman","description":"Provide a clear chronology and evidence.","tip":"Attach bills and final responses."}]$json$::jsonb,
  $json$[{"question":"Does it cost money?","answer":"No — the Energy Ombudsman is free to consumers."},{"question":"Is the decision binding?","answer":"If you accept the outcome, it is binding on the supplier; you can reject and pursue other routes in some cases."}]$json$::jsonb,
  ARRAY['Gas Act 1986','Electricity Act 1989']::text[],
  $json$[{"description":"Typical internal resolution window","days":56,"from_event":"Formal complaint opened"}]$json$::jsonb,
  ARRAY['british-gas','edf','ovo-energy']::text[],
  ARRAY['energy-billing-disputes']::text[],
  'published', now()
),
(
  'ofcom-complaint',
  'How to Complain to Ofcom',
  'How Ofcom regulates telecoms and how consumer complaints reach approved ADR schemes.',
  'ombudsman', 'telecoms',
  $gh$Ofcom’s role in telecoms complaints$gh$,
  $gs$Ofcom sets rules; approved ombudsman schemes resolve many deadlocked disputes.$gs$,
  $gi$Ofcom does not usually resolve individual complaints like a court, but providers must comply with general conditions including complaints handling and access to ADR.$gi$,
  $json$[{"heading":"General conditions","body":"Providers must have complaints codes and tell you about ADR when eligible.","legislation_ref":"Communications Act 2003"}]$json$::jsonb,
  '[]'::jsonb,
  $json$[{"step_number":1,"title":"Complain to your provider","description":"Follow their code of practice.","tip":null},{"step_number":2,"title":"Request a deadlock letter","description":"If stuck after eight weeks or as per rules.","tip":null},{"step_number":3,"title":"ADR referral","description":"Use CISAS or Ombudsman Services as directed.","tip":null}]$json$::jsonb,
  $json$[{"question":"Can Ofcom fine my provider?","answer":"Ofcom can enforce against providers; that is separate from individual redress through ADR."}]$json$::jsonb,
  ARRAY['Communications Act 2003']::text[],
  $json$[{"description":"Typical ADR referral window","days":56,"from_event":"Complaint opened"}]$json$::jsonb,
  ARRAY['bt','ee','sky']::text[],
  ARRAY['broadband-speed-complaints']::text[],
  'published', now()
),
(
  'financial-ombudsman-complaint',
  'How to Complain to the Financial Ombudsman Service',
  'FOS eligibility, DISP timelines, and how to refer banking and credit complaints.',
  'ombudsman', 'financial',
  $gh$Financial Ombudsman Service referrals$gh$,
  $gs$Free dispute resolution for many eligible regulated complaints.$gs$,
  $gi$After a final response from your firm, or after eight weeks for many complaints, you may refer eligible disputes to the Financial Ombudsman Service within published time limits.$gi$,
  $json$[{"heading":"DISP framework","body":"Firms must handle complaints under FCA DISP rules for eligible complaints.","legislation_ref":"FCA Handbook DISP"}]$json$::jsonb,
  $json$[{"criterion":"Eligible complainant","description":"Definitions differ for consumers, micro-enterprises, and charities."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Complain to the firm","description":"Use the internal process.","tip":null},{"step_number":2,"title":"Final response","description":"Check the FOS leaflet enclosed.","tip":null},{"step_number":3,"title":"Refer to FOS","description":"Submit within the time limit stated.","tip":null}]$json$::jsonb,
  $json$[{"question":"Six-month rule?","answer":"FOS applies time limits from your final response — verify the current rules on the FOS website."}]$json$::jsonb,
  ARRAY['Financial Services and Markets Act 2000','FCA Handbook (DISP)']::text[],
  $json$[{"description":"Final response deadline (many complaints)","days":56,"from_event":"Complaint received by firm"}]$json$::jsonb,
  ARRAY['barclays','hsbc','natwest']::text[],
  ARRAY['section-75-claim','chargeback-guide']::text[],
  'published', now()
),
(
  'section-75-claim',
  'Section 75 Claim Guide',
  'Consumer Credit Act 1974 section 75: when your credit card issuer may share liability with the supplier.',
  'legislation', NULL,
  $gh$Section 75 protections on credit card purchases$gh$,
  $gs$May apply to qualifying purchases over £100 on a UK-regulated credit agreement.$gs$,
  $gi$Section 75 can make the creditor jointly liable with the supplier for misrepresentation or breach of contract in certain circumstances. Eligibility is fact-specific.$gi$,
  $json$[{"heading":"Statutory basis","body":"The protection comes from the Consumer Credit Act 1974.","legislation_ref":"Consumer Credit Act 1974 section 75"}]$json$::jsonb,
  $json$[{"criterion":"Minimum amount","description":"Over £100 and usually not more than £30,000 (technical rules apply)."},{"criterion":"Debtor-creditor-supplier chain","description":"The transaction must meet the statutory chain requirements."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Gather evidence","description":"Contracts, adverts, and proof of payment.","tip":null},{"step_number":2,"title":"Claim to card issuer","description":"Write a formal section 75 claim.","tip":null},{"step_number":3,"title":"FOS if deadlocked","description":"If eligible after final response.","tip":null}]$json$::jsonb,
  $json$[{"question":"Does it apply to debit cards?","answer":"Generally no — chargeback is the main card scheme route for debit."}]$json$::jsonb,
  ARRAY['Consumer Credit Act 1974']::text[],
  $json$[{"description":"FOS referral limit from final response","days":180,"from_event":"Final response (verify current FOS rules)"}]$json$::jsonb,
  ARRAY[]::text[],
  ARRAY['chargeback-guide','financial-ombudsman-complaint']::text[],
  'published', now()
),
(
  'consumer-rights-act-2015',
  'Consumer Rights Act 2015: Your Rights',
  'Core UK consumer rights for goods, services, and unfair terms under the Consumer Rights Act 2015.',
  'legislation', NULL,
  $gh$Consumer Rights Act 2015 essentials$gh$,
  $gs$Sets statutory rights for faulty goods, substandard services, and unfair contract terms.$gs$,
  $gi$The CRA 2015 consolidates and updates consumer law for most business-to-consumer contracts in the UK.$gi$,
  $json$[{"heading":"Goods must be satisfactory","body":"Goods must be as described, fit for purpose, and of satisfactory quality.","legislation_ref":"Consumer Rights Act 2015"}]$json$::jsonb,
  '[]'::jsonb,
  $json$[{"step_number":1,"title":"Identify the problem","description":"Good, digital content, or service failure.","tip":null},{"step_number":2,"title":"Remedy route","description":"Repair, replacement, price reduction, or repeat performance depending on context.","tip":null},{"step_number":3,"title":"Escalate","description":"ADR, ombudsman, or court as appropriate.","tip":null}]$json$::jsonb,
  $json$[{"question":"Is there always a refund?","answer":"Remedies depend on timing and whether the fault is minor — check Citizens Advice summaries."}]$json$::jsonb,
  ARRAY['Consumer Rights Act 2015']::text[],
  '[]'::jsonb,
  ARRAY[]::text[],
  ARRAY['deadlock-letter']::text[],
  'published', now()
),
(
  'flight-delay-compensation',
  'Flight Delay Compensation Guide',
  'UK261 / retained EU261: when compensation may be due for delay, cancellation, and denied boarding.',
  'rights', 'travel',
  $gh$UK flight disruption compensation basics$gh$,
  $gs$Compensation depends on distance, delay length, and whether the flight falls under UK261.$gs$,
  $gi$UK261 provides a structured regime for many qualifying flights from UK carriers and flights departing the UK, subject to specific tests and defences.$gi$,
  $json$[{"heading":"Key cases","body":"Court decisions such as Huzar v Jet2 shaped how extraordinary circumstances are interpreted — verify current guidance.","legislation_ref":"UK261"}]$json$::jsonb,
  $json$[{"criterion":"Qualifying flight","description":"Check departure/arrival and carrier rules."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Collect proof","description":"Boarding pass, delay announcement, emails.","tip":null},{"step_number":2,"title":"Claim from airline","description":"Use the carrier’s EU261/UK261 form.","tip":null},{"step_number":3,"title":"ADR or court","description":"If refused and you remain eligible.","tip":null}]$json$::jsonb,
  $json$[{"question":"Food and hotel costs?","answer":"Care and assistance rules apply in many qualifying delays — check UK261 text and CAA guidance."}]$json$::jsonb,
  ARRAY['UK261 (retained EU Regulation 261/2004)']::text[],
  $json$[{"description":"Limitation for court claims","days":1095,"from_event":"Flight date (verify limitation rules)"}]$json$::jsonb,
  ARRAY['british-airways','easyjet','ryanair']::text[],
  ARRAY['consumer-rights-act-2015']::text[],
  'published', now()
),
(
  'chargeback-guide',
  'Chargeback Guide',
  'Visa and Mastercard chargeback: a card-scheme dispute route separate from section 75.',
  'process', 'financial',
  $gh$Chargeback disputes on card payments$gh$,
  $gs$Banks raise disputes through card scheme rules — not identical to section 75.$gs$,
  $gi$Chargeback can help where goods or services were not provided or were defective, subject to scheme reason codes and issuer discretion.$gi$,
  $json$[{"heading":"Scheme rules","body":"Visa and Mastercard maintain chargeback reason codes and time limits.","legislation_ref":"Visa/Mastercard scheme rules"}]$json$::jsonb,
  $json$[{"criterion":"Time limits","description":"Often 120 days from expected delivery — confirm with your issuer."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Contact your bank","description":"Request chargeback with evidence.","tip":null},{"step_number":2,"title":"Issuer investigation","description":"The merchant may respond.","tip":null},{"step_number":3,"title":"Outcome","description":"Temporary credit may be reversed if the dispute fails.","tip":null}]$json$::jsonb,
  $json$[{"question":"Chargeback vs section 75?","answer":"They are different mechanisms; sometimes both are explored with professional guidance."}]$json$::jsonb,
  ARRAY['Visa/Mastercard scheme rules']::text[],
  $json$[{"description":"Typical chargeback window","days":120,"from_event":"Expected delivery or service date"}]$json$::jsonb,
  ARRAY['barclays','hsbc']::text[],
  ARRAY['section-75-claim']::text[],
  'published', now()
),
(
  'deadlock-letter',
  'How to Get a Deadlock Letter',
  'What a deadlock letter is and how it unlocks ombudsman and ADR routes across sectors.',
  'process', NULL,
  $gh$Deadlock letters explained$gh$,
  $gs$A clear “final position” can start the clock for external dispute resolution.$gs$,
  $gi$Many ombudsman schemes require a final response or a defined complaint age. A deadlock letter states the business will not change its position.$gi$,
  $json$[{"heading":"Why it matters","body":"It can demonstrate you have exhausted internal processes.","legislation_ref":"Various ombudsman scheme rules"}]$json$::jsonb,
  '[]'::jsonb,
  $json$[{"step_number":1,"title":"Ask in writing","description":"Request a written final response.","tip":null},{"step_number":2,"title":"Set out remaining issues","description":"Bullet unresolved points.","tip":null},{"step_number":3,"title":"Escalate","description":"Use the scheme named in the letter.","tip":null}]$json$::jsonb,
  $json$[{"question":"Can I invent a deadlock?","answer":"No — it should reflect the firm’s genuine final position; misrepresentation can harm your case."}]$json$::jsonb,
  ARRAY[]::text[],
  '[]'::jsonb,
  ARRAY[]::text[],
  ARRAY['energy-ombudsman-escalation','financial-ombudsman-complaint']::text[],
  'published', now()
),
(
  'energy-billing-disputes',
  'Energy Billing Disputes Guide',
  'Back-billing, estimates, and wrong tariffs: how energy billing complaints are regulated.',
  'rights', 'energy',
  $gh$Challenge incorrect energy bills$gh$,
  $gs$Licence conditions and standards limit certain back-billing and require fair treatment.$gs$,
  $gi$If your bill looks wrong, you can challenge it with evidence. Ofgem rules on back-billing and customer service standards often apply.$gi$,
  $json$[{"heading":"Back-billing rules","body":"Suppliers must follow Ofgem back-billing rules for domestic consumers in many situations.","legislation_ref":"Ofgem back-billing rules"}]$json$::jsonb,
  '[]'::jsonb,
  $json$[{"step_number":1,"title":"Check meter data","description":"Compare opening/closing reads.","tip":null},{"step_number":2,"title":"Formal complaint","description":"Ask for a written calculation.","tip":null},{"step_number":3,"title":"Ombudsman","description":"If eligible after the process.","tip":null}]$json$::jsonb,
  $json$[{"question":"Can they back-bill years?","answer":"Ofgem caps apply in many domestic cases — verify the current cap and exceptions."}]$json$::jsonb,
  ARRAY['Gas Act 1986','Electricity Act 1989']::text[],
  $json$[{"description":"Typical supplier resolution target","days":56,"from_event":"Formal complaint"}]$json$::jsonb,
  ARRAY['british-gas','octopus-energy']::text[],
  ARRAY['energy-ombudsman-escalation']::text[],
  'published', now()
),
(
  'broadband-speed-complaints',
  'Broadband Speed Complaints',
  'Voluntary codes and Ofcom rules on speeds, estimates, and what to do when performance falls short.',
  'rights', 'telecoms',
  $gh$When broadband speed promises are missed$gh$,
  $gs$Ofcom codes and contract terms shape refunds and exits for speed problems.$gs$,
  $gi$Providers often give estimates and minimum guaranteed speeds. Persistent faults below guarantees may trigger rights to leave or compensation under applicable codes.$gi$,
  $json$[{"heading":"Voluntary codes","body":"Major providers follow Ofcom-brokered broadband speed codes — confirm your provider’s version.","legislation_ref":"Ofcom voluntary speed codes"}]$json$::jsonb,
  $json$[{"criterion":"Guaranteed speed","description":"Check your contract for the minimum guaranteed line speed."}]$json$::jsonb,
  $json$[{"step_number":1,"title":"Run wired tests","description":"Follow provider troubleshooting.","tip":"Use Ethernet where possible."},{"step_number":2,"title":"Log faults","description":"Engineer visits and ticket IDs.","tip":null},{"step_number":3,"title":"ADR","description":"If deadlocked after eight weeks.","tip":null}]$json$::jsonb,
  $json$[{"question":"Wi-Fi vs line speed?","answer":"Guarantees usually refer to the line into the home — Wi-Fi issues can be separate."}]$json$::jsonb,
  ARRAY['Communications Act 2003']::text[],
  $json$[{"description":"ADR referral","days":56,"from_event":"Complaint opened"}]$json$::jsonb,
  ARRAY['bt','sky','virgin-media']::text[],
  ARRAY['ofcom-complaint']::text[],
  'published', now()
)
ON CONFLICT (slug) DO NOTHING;
