-- 11E-1: Broadband Speed guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'broadband-speed',
  'broadband_speed',
  'Broadband Speed Dispute',
  'Step-by-step guide to resolving a broadband speed complaint, from gathering speed test evidence through to ADR referral via CISAS or Ombudsman Services.',
  'telecoms',
  true,
  $steps$
[
  {"step_id": "gather-speed-evidence", "order": 1, "title": "Gather your speed test evidence", "description": "Before contacting your provider, you need solid evidence that your broadband speed is consistently below what was promised. Run speed tests at different times of day over several days to build a clear picture.", "action_type": "checklist", "action_config": {"items": ["Check your contract for your guaranteed minimum download speed (look for the phrase \"minimum guaranteed speed\" — this is the key figure, not the \"up to\" or \"estimated\" speed)", "Run speed tests using a wired connection (not Wi-Fi) at broadband.ofcom.org.uk or speedtest.net — at least 3 tests at different times of day over 3 separate days", "Screenshot or save each speed test result with the date and time visible", "Upload your speed test results as evidence on this case", "Note your router model and confirm it is the one provided or recommended by your ISP"], "tip": "Wi-Fi speeds are always lower than wired speeds and your ISP will use this to dismiss your complaint. Always test with an ethernet cable plugged directly into your router."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint"},
  {"step_id": "initial-complaint", "order": 2, "title": "Send your formal complaint", "description": "We have drafted a complaint letter to {company_name} that references your speed test evidence and your contractual minimum guaranteed speed. This letter formally opens the complaint and starts the 8-week clock for ADR eligibility.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "broadband_speed_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Give {company_name} 14 days to respond. They may offer to send an engineer or run remote diagnostics. Log any response or contact you receive.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 3, "title": "What happened?", "description": "It has been 14 days since your complaint. Did {company_name} respond, and if so, has the issue been resolved?", "action_type": "branch", "action_config": {"question": "How did your broadband provider respond?", "options": [{"label": "They fixed the speed — resolved", "next_step": "resolved"}, {"label": "They sent an engineer but the speed is still poor", "next_step": "post-engineer"}, {"label": "They offered a partial solution (e.g. discount, lower tariff)", "next_step": "right-to-exit"}, {"label": "No meaningful response", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "post-engineer", "order": 4, "title": "Re-test after the engineer visit", "description": "An engineer visited but your speed may still be below the guaranteed minimum. Run fresh speed tests over the next 3 days using the same wired connection method. If speeds are still below the guaranteed minimum, you can proceed with a follow-up complaint.", "action_type": "checklist", "action_config": {"items": ["Run 3 new speed tests over 3 days (wired connection, different times of day)", "Upload the new speed test results as evidence", "Log what the engineer did and any explanation they gave"]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 3, "wait_message": "Test your speeds over the next few days. If the problem persists, we will help you escalate.", "next_step": "follow-up"},
  {"step_id": "right-to-exit", "order": 5, "title": "Consider your right to exit", "description": "If your provider has signed Ofcom's Voluntary Code of Practice on Broadband Speeds and cannot deliver the minimum guaranteed speed, you have the right to exit your contract without paying an early termination fee. You can use this as leverage: either fix the speed or let you leave penalty-free.", "action_type": "info", "action_config": {"tip": "Most major UK ISPs (BT, Sky, TalkTalk, Plusnet, EE, Vodafone, Virgin Media) have signed the code. If your provider has not signed it, you still have rights under the Consumer Rights Act 2015 — the service must be provided with reasonable care and skill."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "follow-up", "order": 6, "title": "Send a follow-up letter", "description": "Your complaint has not been resolved. This follow-up letter references your ongoing speed evidence, notes the inadequate response, invokes your right to exit under Ofcom's code (if applicable), and warns of ADR escalation.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "broadband_speed_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "Another 14 days for {company_name} to act. If they still cannot fix the issue, we will prepare your ADR referral.", "next_step": "assess-response-2"},
  {"step_id": "assess-response-2", "order": 7, "title": "Final check before ADR", "description": "Has {company_name} resolved the speed issue after your follow-up?", "action_type": "branch", "action_config": {"question": "What is the current situation?", "options": [{"label": "Resolved — speed is now acceptable", "next_step": "resolved"}, {"label": "They let me exit without penalty", "next_step": "resolved"}, {"label": "Still unresolved — I want to escalate", "next_step": "deadlock-or-8-weeks"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "deadlock-or-8-weeks"},
  {"step_id": "deadlock-or-8-weeks", "order": 8, "title": "Request a deadlock letter or wait for 8 weeks", "description": "You can escalate to ADR once 8 weeks have passed since your original complaint, or sooner if {company_name} issues a deadlock letter. Check which ADR scheme your provider belongs to — this information is on Ofcom's website at ofcom.org.uk/phones-and-broadband/how-to-complain or on your provider's own complaints page.", "action_type": "info", "action_config": {"check_8_week_deadline": true, "tip": "Most providers are members of either CISAS (cedr.com/consumer/cisas) or Ombudsman Services: Communications (ombudsman-services.org/sectors/communications). Your provider must tell you which scheme they belong to if you ask. Check before proceeding so you submit to the correct scheme."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Tracking the 8-week deadline from your initial complaint. We will notify you when you are eligible to escalate.", "next_step": "adr-referral"},
  {"step_id": "adr-referral", "order": 9, "title": "Submit your ADR complaint", "description": "You are now eligible to escalate to Alternative Dispute Resolution. We have prepared your referral letter and a full case summary PDF with your timeline, speed test evidence, and correspondence history. Submit this to your provider's ADR scheme.", "action_type": "escalate", "action_config": {"letter_type": "adr_referral", "auto_generate": true, "prompt_context": "broadband_speed_adr", "export_pdf": true, "escalation_target": "CISAS or Ombudsman Services: Communications", "escalation_url": "https://www.ofcom.org.uk/phones-and-broadband/how-to-complain", "escalation_method": "Online form — check your provider's ADR scheme first"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "ADR decisions typically take 6-8 weeks. Log any correspondence you receive.", "next_step": "awaiting-adr"},
  {"step_id": "awaiting-adr", "order": 10, "title": "Await the ADR decision", "description": "Your complaint is now with the ADR scheme. They will investigate and issue a decision. The decision is binding on {company_name} if you accept it, but you are not obliged to accept — you can reject it and pursue the matter through the courts if you prefer.", "action_type": "wait", "action_config": {"tip": "If the ADR scheme finds in your favour, your provider must comply. Remedies can include fixing the service, allowing you to exit the contract, refunding charges, or paying compensation."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Well done for seeing this through. Record your outcome to help other broadband customers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
