-- 11E-2: Flight Delay / Cancellation Compensation guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'flight-delay',
  'flight_delay',
  'Flight Delay or Cancellation Compensation',
  'Step-by-step guide to claiming compensation for a delayed or cancelled flight under UK261/EU261 regulations.',
  'travel',
  true,
  $steps$
[
  {"step_id": "check-eligibility", "order": 1, "title": "Check your eligibility", "description": "Not all flight delays qualify for compensation. Answer these questions to confirm your claim is valid before proceeding.", "action_type": "checklist", "action_config": {"items": ["Confirm your flight was delayed by 3 or more hours at your final destination (or was cancelled, or you were denied boarding)", "Confirm the flight departed from a UK or EU airport, OR arrived at a UK/EU airport on a UK/EU carrier", "Confirm the flight was within the last 6 years (5 years if you live in Scotland)", "Check whether the delay was caused by extraordinary circumstances (severe weather, air traffic control strike, volcanic ash, security threat) — if so, compensation may not be available, but you should still claim as airlines often cite this incorrectly", "Find your booking confirmation or e-ticket showing the flight number, date, and route"], "tip": "Technical faults, crew shortages, missed connecting flights due to the airline's scheduling, and IT failures are NOT extraordinary circumstances — the airline owes you compensation for these. Airlines frequently claim extraordinary circumstances incorrectly. If in doubt, proceed with the claim."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "calculate-compensation"},
  {"step_id": "calculate-compensation", "order": 2, "title": "Calculate your compensation", "description": "Your compensation amount depends on the flight distance. Use the TheyPromised compensation calculator to determine the amount, or refer to the standard rates: under 1,500km = £220, 1,500-3,500km = £350, over 3,500km = £520. Note: if you were offered re-routing that arrived within 2-4 hours of the original arrival time (depending on distance), the airline may reduce compensation by 50%.", "action_type": "info", "action_config": {"compensation_table": [{"distance": "Under 1,500km (short haul)", "amount": "£220 / €250"}, {"distance": "1,500 — 3,500km (medium haul)", "amount": "£350 / €400"}, {"distance": "Over 3,500km (long haul)", "amount": "£520 / €600"}], "tip": "Use a flight distance calculator (e.g. webflyer.com/travel/mileage_calculator) to check the great circle distance between your departure and arrival airports. This is the distance used for compensation, not the actual route flown."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "gather-evidence"},
  {"step_id": "gather-evidence", "order": 3, "title": "Gather your evidence", "description": "Collect all evidence related to your disrupted flight before sending your claim.", "action_type": "checklist", "action_config": {"items": ["Upload your booking confirmation or e-ticket", "Upload your boarding pass (if you have it)", "Note the actual departure and arrival times (check your airline's app, Flightradar24, or FlightAware for the actual times)", "Save any communication from the airline about the delay or cancellation (emails, SMS, app notifications)", "Keep receipts for any expenses incurred due to the delay (food, accommodation, transport) — you may be able to claim these separately under the airline's duty of care obligations", "If you were offered re-routing, note the alternative flight details and actual arrival time"]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-claim"},
  {"step_id": "initial-claim", "order": 4, "title": "Send your compensation claim", "description": "We have drafted a formal compensation claim to {company_name}. This letter cites your rights under UK261 (or EU261), specifies the compensation amount, and includes your flight details and evidence.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "flight_delay_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 28, "wait_message": "Airlines often take several weeks to respond to compensation claims. We have set a 28-day deadline. Many airlines have an online claims portal — if you submitted through their portal as well, log that interaction.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 5, "title": "How did the airline respond?", "description": "Check whether {company_name} has responded to your claim.", "action_type": "branch", "action_config": {"question": "What happened after your claim?", "options": [{"label": "They paid the full compensation", "next_step": "resolved"}, {"label": "They offered a partial amount or vouchers", "next_step": "reject-partial"}, {"label": "They refused, citing extraordinary circumstances", "next_step": "challenge-refusal"}, {"label": "No response", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "reject-partial", "order": 6, "title": "Reject the partial offer", "description": "Airlines sometimes offer vouchers, reduced amounts, or loyalty points instead of the cash compensation you are legally entitled to. You are under no obligation to accept these. UK261/EU261 entitles you to cash compensation at the fixed rates.", "action_type": "info", "action_config": {"tip": "Do not accept vouchers or reduced offers unless you are genuinely happy with them. Once you accept, it may be harder to claim the full amount. Your legal entitlement is cash compensation at the fixed rate, not vouchers or air miles."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "challenge-refusal", "order": 7, "title": "Challenge the extraordinary circumstances claim", "description": "The airline has claimed the delay was caused by extraordinary circumstances. This is the most common reason for refusal, and airlines frequently cite it incorrectly. Technical faults, crew shortages, IT failures, and operational issues are NOT extraordinary circumstances under established case law.", "action_type": "info", "action_config": {"tip": "Key case law: Huzar v Jet2 (2014) — technical faults are inherent in normal airline operations. Van der Lans v KLM (2015) — unexpected technical problems are not extraordinary circumstances. If the airline cited a technical fault, crew issue, or operational problem, their refusal is likely invalid."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "follow-up", "order": 8, "title": "Send a follow-up letter", "description": "This follow-up rejects any inadequate offer or challenges the airline's refusal. It references the relevant case law, restates your legal entitlement, and warns of ADR escalation.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "flight_delay_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 more days for {company_name} to reconsider. If they still refuse, you can escalate to ADR.", "next_step": "assess-response-2"},
  {"step_id": "assess-response-2", "order": 9, "title": "Final check before ADR", "description": "Has {company_name} paid your compensation?", "action_type": "branch", "action_config": {"question": "What happened after your follow-up?", "options": [{"label": "They paid the full amount", "next_step": "resolved"}, {"label": "Still refusing or no response", "next_step": "deadlock-or-8-weeks"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "deadlock-or-8-weeks"},
  {"step_id": "deadlock-or-8-weeks", "order": 10, "title": "Wait for 8 weeks or request a deadlock letter", "description": "You can escalate to ADR once 8 weeks have passed since your original claim. Most UK airlines use AviationADR (operated by CEDR). Check which ADR scheme {company_name} belongs to at aviationadr.org.uk or on the CAA website.", "action_type": "info", "action_config": {"check_8_week_deadline": true, "tip": "You can also complain to the CAA (Civil Aviation Authority) at caa.co.uk/passengers — they cannot award compensation directly but can investigate the airline and put pressure on them. Consider submitting a CAA complaint in parallel with your ADR referral."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Tracking the 8-week deadline. We will notify you when you can escalate.", "next_step": "adr-referral"},
  {"step_id": "adr-referral", "order": 11, "title": "Submit your ADR complaint", "description": "We have prepared your ADR referral with a complete case summary, all evidence, and your correspondence history. Submit this to AviationADR (or whichever scheme your airline belongs to).", "action_type": "escalate", "action_config": {"letter_type": "adr_referral", "auto_generate": true, "prompt_context": "flight_delay_adr", "export_pdf": true, "escalation_target": "AviationADR (CEDR)", "escalation_url": "https://www.aviationadr.org.uk/", "escalation_method": "Online form at aviationadr.org.uk"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "ADR typically takes 4-8 weeks. Log any correspondence.", "next_step": "awaiting-adr"},
  {"step_id": "awaiting-adr", "order": 12, "title": "Await the ADR decision", "description": "Your claim is now with the ADR scheme. Their decision is binding on {company_name} if you accept it. If you reject it, you can still take the airline to the small claims court. Most flight delay claims are straightforward and succeed at ADR if your evidence is solid.", "action_type": "wait", "action_config": {"tip": "If ADR rules in your favour and the airline still does not pay, you can enforce the decision through the county court. This is rare — airlines almost always comply with ADR decisions."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Record your outcome to help other air passengers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
