-- 11E-3: Bank Charges dispute guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'bank-charges',
  'bank_charges',
  'Bank Charges Dispute',
  'Step-by-step guide to disputing unfair or incorrect bank charges, from formal complaint through to the Financial Ombudsman Service.',
  'finance',
  true,
  $steps$
[
  {"step_id": "gather-evidence", "order": 1, "title": "Gather your evidence", "description": "Before contacting your bank, collect all evidence of the charges you are disputing.", "action_type": "checklist", "action_config": {"items": ["Download or screenshot your bank statements showing the disputed charges — highlight or note the specific charges", "Calculate the total amount you believe was charged unfairly or incorrectly", "Check your account terms and conditions for the relevant fee schedule", "Note any previous communication with the bank about these charges", "If charges resulted from a bank error (e.g. failed to process a payment, applied the wrong interest rate), document the error and its impact"], "tip": "Request a full statement of charges from your bank if you need a longer history. Under the Data Protection Act 2018 (GDPR), they must provide this within one month, usually free of charge."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint"},
  {"step_id": "initial-complaint", "order": 2, "title": "Send your formal complaint", "description": "We have drafted a formal complaint to {company_name} disputing the charges and requesting a refund. This letter starts the 8-week clock for Financial Ombudsman eligibility.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "bank_charges_initial"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Your bank should acknowledge your complaint within a few days. They have up to 8 weeks to provide a final response. Log any communication you receive.", "next_step": "assess-response-1"},
  {"step_id": "assess-response-1", "order": 3, "title": "Has the bank responded?", "description": "Check whether {company_name} has acknowledged or responded to your complaint.", "action_type": "branch", "action_config": {"question": "What has happened so far?", "options": [{"label": "They refunded the charges in full", "next_step": "resolved"}, {"label": "They offered a partial refund", "next_step": "consider-partial"}, {"label": "They rejected my complaint", "next_step": "follow-up"}, {"label": "They acknowledged but have not resolved it yet", "next_step": "wait-for-final-response"}, {"label": "No response at all", "next_step": "follow-up"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "consider-partial", "order": 4, "title": "Consider the partial offer", "description": "The bank has offered a partial refund. Consider whether this is acceptable. If the full amount is significant and you believe you are entitled to it, you can reject the offer and escalate. The Financial Ombudsman can award the full amount if your claim is valid.", "action_type": "info", "action_config": {"tip": "If the bank's partial offer is close to what you claimed and the remaining amount is small, it may be more practical to accept. If the gap is large, proceed with the follow-up and escalation. You will not be penalised by the Ombudsman for rejecting a partial offer."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up"},
  {"step_id": "wait-for-final-response", "order": 5, "title": "Wait for the bank's final response", "description": "The bank has acknowledged your complaint and is investigating. Under FCA rules, they must send you a final response within 8 weeks. If they cannot resolve it within that time, they must send you a letter explaining why and telling you about your right to go to the Financial Ombudsman.", "action_type": "wait", "action_config": {"check_8_week_deadline": true, "tip": "If you receive a 'final response letter' before 8 weeks, read it carefully. If you are unhappy with the outcome, you have 6 months from the date of that letter to refer your complaint to the Financial Ombudsman."}, "completion_criteria": {"type": "days_passed", "reference": "initial_complaint_date", "days": 56}, "wait_after_days": 0, "wait_message": "Waiting for the bank's final response. The 8-week deadline is tracked automatically.", "next_step": "assess-final-response"},
  {"step_id": "assess-final-response", "order": 6, "title": "Review the bank's final response", "description": "The 8-week period has passed or you have received a final response letter. What happened?", "action_type": "branch", "action_config": {"question": "What is the current status?", "options": [{"label": "Resolved — I got a full refund", "next_step": "resolved"}, {"label": "Final response received but I am not satisfied", "next_step": "fos-referral"}, {"label": "8 weeks passed with no final response", "next_step": "fos-referral"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "fos-referral"},
  {"step_id": "follow-up", "order": 7, "title": "Send a follow-up letter", "description": "Your complaint was either rejected or ignored. This follow-up references the original complaint, challenges the bank's position, and warns of escalation to the Financial Ombudsman.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "bank_charges_followup"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 more days for {company_name} to reconsider before escalation.", "next_step": "wait-for-final-response"},
  {"step_id": "fos-referral", "order": 8, "title": "Refer to the Financial Ombudsman Service", "description": "You are now eligible to escalate to the Financial Ombudsman Service (FOS). We have prepared your referral with a complete case summary, evidence, and correspondence history. FOS is free to use and their decisions are binding on the bank.", "action_type": "escalate", "action_config": {"letter_type": "ombudsman_referral", "auto_generate": true, "prompt_context": "bank_charges_fos", "export_pdf": true, "escalation_target": "Financial Ombudsman Service", "escalation_url": "https://www.financial-ombudsman.org.uk/consumers/how-to-complain", "escalation_method": "Online form, phone (0800 023 4567), or post"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "wait_message": "FOS investigations typically take several months. Log any correspondence. FOS may contact you for additional information or to discuss a settlement.", "next_step": "awaiting-fos"},
  {"step_id": "awaiting-fos", "order": 9, "title": "Await the Ombudsman decision", "description": "Your complaint is with the Financial Ombudsman Service. An adjudicator will review the case and make an initial assessment. If either side disagrees, an ombudsman will make a final decision. The decision is binding on the bank if you accept it.", "action_type": "wait", "action_config": {"tip": "FOS will first try to resolve the complaint informally. If the adjudicator's initial assessment goes against you, you can request a final decision from an ombudsman — this is a different, more senior person. Do not give up at the adjudicator stage if you believe your case is strong."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Record your outcome to help other bank customers know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
