-- 11E-4: Faulty Product (Consumer Rights Act 2015) guided journey
INSERT INTO journey_templates (id, category, title, description, sector, is_active, steps) VALUES (
  'faulty-product',
  'faulty_product',
  'Faulty Product Complaint',
  'Step-by-step guide to getting a refund, repair, or replacement for a faulty product under the Consumer Rights Act 2015.',
  'retail',
  true,
  $steps$
[
  {"step_id": "assess-timeline", "order": 1, "title": "When did you buy the product?", "description": "Your rights depend on how long ago you bought the product. This determines which remedy you should pursue first.", "action_type": "branch", "action_config": {"question": "How long ago did you purchase the product?", "options": [{"label": "Less than 30 days ago", "next_step": "short-term-reject"}, {"label": "30 days to 6 months ago", "next_step": "repair-or-replace"}, {"label": "More than 6 months ago", "next_step": "long-term-claim"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "short-term-reject"},
  {"step_id": "short-term-reject", "order": 2, "title": "Exercise your short-term right to reject", "description": "You bought this product less than 30 days ago. Under section 22 of the Consumer Rights Act 2015, you have an absolute right to reject the goods for a full refund. The retailer cannot insist on a repair or replacement — you are entitled to your money back.", "action_type": "checklist", "action_config": {"items": ["Confirm the product is genuinely faulty, not as described, or not fit for purpose", "Find your proof of purchase (receipt, order confirmation email, bank statement showing the transaction)", "Upload photos or videos showing the fault", "Stop using the product if possible (continued use after discovering the fault could weaken your right to reject)"], "tip": "You do NOT need the original packaging. The retailer cannot refuse a return because you have lost the box. You just need proof of purchase."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-reject"},
  {"step_id": "repair-or-replace", "order": 3, "title": "Request a repair or replacement", "description": "Your product is between 30 days and 6 months old. Under the Consumer Rights Act 2015, you are entitled to a repair or replacement. The retailer must do this within a reasonable time and without significant inconvenience to you. If the first repair or replacement fails, you have the right to a price reduction or to reject the goods.", "action_type": "checklist", "action_config": {"items": ["Find your proof of purchase", "Upload photos or videos showing the fault", "Decide whether you want a repair or replacement (you can choose, but the retailer can refuse if your choice is disproportionately expensive compared to the alternative)", "Note: during this period, the burden of proof is on the retailer — the product is presumed to have been faulty at delivery unless they can prove otherwise"], "tip": "If the retailer claims the fault is due to misuse, they must prove it. You do not need to prove the product was faulty when you bought it during the first 6 months."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-repair"},
  {"step_id": "long-term-claim", "order": 4, "title": "Gather evidence of the inherent fault", "description": "Your product is more than 6 months old. You can still claim under the Consumer Rights Act 2015, but the burden of proof is now on you — you need to show that the fault was present at delivery or is due to an inherent defect in the product, not normal wear and tear or misuse.", "action_type": "checklist", "action_config": {"items": ["Find your proof of purchase", "Upload photos or videos showing the fault", "Consider whether the fault is clearly a manufacturing defect or inherent problem (e.g. a washing machine motor failing after 8 months is likely inherent; a cracked phone screen from being dropped is not)", "If the product is expensive, consider getting an independent expert report or opinion (this can strengthen your case but is not always necessary)", "Check online for other customers reporting the same fault — a known issue strengthens your position"], "tip": "Products should last a reasonable amount of time. A £1,200 laptop failing after 7 months is not reasonable even if the warranty has expired. Your statutory rights under the CRA are separate from any manufacturer warranty."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "initial-complaint-repair"},
  {"step_id": "initial-complaint-reject", "order": 5, "title": "Send your rejection letter", "description": "We have drafted a formal letter to {company_name} rejecting the faulty goods and requesting a full refund under section 22 of the Consumer Rights Act 2015.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "faulty_product_reject"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 14, "wait_message": "Give {company_name} 14 days to process your refund. If they refuse or ignore you, we will help you escalate.", "next_step": "assess-response-1"},
  {"step_id": "initial-complaint-repair", "order": 6, "title": "Send your complaint requesting a remedy", "description": "We have drafted a formal complaint to {company_name} requesting a repair or replacement under the Consumer Rights Act 2015.", "action_type": "send_letter", "action_config": {"letter_type": "initial_complaint", "auto_generate": true, "prompt_context": "faulty_product_repair"}, "completion_criteria": {"type": "letter_sent", "letter_type": "initial_complaint"}, "wait_after_days": 21, "wait_message": "Give {company_name} a reasonable time to arrange the repair or replacement. 21 days is generally considered reasonable. Log any communication.", "next_step": "assess-repair-response"},
  {"step_id": "assess-response-1", "order": 7, "title": "Did they accept the rejection?", "description": "Has {company_name} processed your refund?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Full refund received", "next_step": "resolved"}, {"label": "They offered a repair or replacement instead of a refund", "next_step": "insist-refund"}, {"label": "They refused entirely", "next_step": "follow-up-reject"}, {"label": "No response", "next_step": "follow-up-reject"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "insist-refund", "order": 8, "title": "You are entitled to a refund, not just a repair", "description": "Within the first 30 days, the retailer CANNOT insist on a repair or replacement. Your short-term right to reject is absolute under section 22 of the Consumer Rights Act 2015. The retailer is misstating your rights.", "action_type": "info", "action_config": {"tip": "This is one of the most common ways retailers try to avoid giving refunds. They will say 'our policy is to repair first' or 'we need to send it to the manufacturer.' Your statutory rights override any store policy. The law is clear: within 30 days, you choose the refund."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "assess-repair-response", "order": 9, "title": "Was the repair or replacement successful?", "description": "Did {company_name} repair or replace the product, and does it now work properly?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Repaired/replaced and working fine", "next_step": "resolved"}, {"label": "Repair failed — still faulty", "next_step": "final-right-to-reject"}, {"label": "They refused to repair or replace", "next_step": "follow-up-repair"}, {"label": "No response or unreasonable delay", "next_step": "follow-up-repair"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-repair"},
  {"step_id": "final-right-to-reject", "order": 10, "title": "Exercise your final right to reject", "description": "The first repair or replacement has failed. Under section 24 of the Consumer Rights Act 2015, you now have the final right to reject the goods for a refund (subject to a deduction for the use you have had) or to request a price reduction.", "action_type": "info", "action_config": {"tip": "The retailer can make a reasonable deduction for the use you have had of the product, but the deduction must be fair. For example, if a £500 washing machine failed after 4 months and the expected lifespan is 7 years, a fair deduction for use might be around £24 (4/84 months). The deduction cannot reduce your refund to zero."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "follow-up-reject"},
  {"step_id": "follow-up-reject", "order": 11, "title": "Send a follow-up insisting on your refund", "description": "This letter firmly restates your right to a refund, references the specific section of the Consumer Rights Act 2015, and warns of further action if the retailer does not comply.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "faulty_product_followup_reject"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 days for {company_name} to process the refund. If they still refuse, we will explore your escalation options.", "next_step": "escalation-options"},
  {"step_id": "follow-up-repair", "order": 12, "title": "Send a follow-up about the failed repair", "description": "This letter notes the retailer's failure to provide a timely repair or replacement and asserts your right to a price reduction or rejection.", "action_type": "send_letter", "action_config": {"letter_type": "follow_up", "auto_generate": true, "prompt_context": "faulty_product_followup_repair"}, "completion_criteria": {"type": "letter_sent", "letter_type": "follow_up"}, "wait_after_days": 14, "wait_message": "14 days for {company_name} to arrange a remedy.", "next_step": "escalation-options"},
  {"step_id": "escalation-options", "order": 13, "title": "Consider your escalation options", "description": "The retailer has refused to honour your consumer rights. Unlike energy, broadband, or banking, there is no ombudsman for general retail. Your options depend on how you paid and the value of the claim.", "action_type": "branch", "action_config": {"question": "How did you pay for the product?", "options": [{"label": "Credit card (and the item cost over £100)", "next_step": "section-75"}, {"label": "Debit card", "next_step": "chargeback"}, {"label": "Cash, bank transfer, or other", "next_step": "small-claims"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "small-claims"},
  {"step_id": "section-75", "order": 14, "title": "Make a Section 75 claim with your credit card provider", "description": "If you paid by credit card and the item cost between £100 and £30,000, your credit card provider is jointly liable for the breach of contract under section 75 of the Consumer Credit Act 1974. This means you can claim the refund from your card provider instead of (or as well as) the retailer.", "action_type": "send_letter", "action_config": {"letter_type": "section_75_claim", "auto_generate": true, "prompt_context": "faulty_product_section75"}, "completion_criteria": {"type": "letter_sent", "letter_type": "section_75_claim"}, "wait_after_days": 28, "wait_message": "Card providers typically take 2-4 weeks to process Section 75 claims. If they refuse, you can escalate to the Financial Ombudsman Service.", "next_step": "assess-section-75"},
  {"step_id": "chargeback", "order": 15, "title": "Request a chargeback from your bank", "description": "If you paid by debit card, you can request a chargeback through your bank. This is not a statutory right (it is a scheme rule from Visa/Mastercard), but banks generally process these. Contact your bank and explain that the retailer has breached the Consumer Rights Act 2015 by refusing to remedy a faulty product.", "action_type": "info", "action_config": {"tip": "Chargebacks usually must be initiated within 120 days of the transaction (or 120 days from when you discovered the fault, depending on the card scheme). Act quickly. If the chargeback fails or is disputed by the retailer, the small claims court is your next option."}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "small-claims"},
  {"step_id": "assess-section-75", "order": 16, "title": "Did the card provider refund you?", "description": "What was the outcome of your Section 75 claim?", "action_type": "branch", "action_config": {"question": "What happened?", "options": [{"label": "Refund received", "next_step": "resolved"}, {"label": "Claim rejected — I want to escalate", "next_step": "fos-section75"}, {"label": "Still waiting", "next_step": "assess-section-75"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "fos-section75"},
  {"step_id": "fos-section75", "order": 17, "title": "Escalate to the Financial Ombudsman", "description": "Your credit card provider rejected your Section 75 claim. Because they are an FCA-regulated firm, you can escalate to the Financial Ombudsman Service. Follow the same 8-week complaint process as for a bank complaint.", "action_type": "escalate", "action_config": {"letter_type": "ombudsman_referral", "auto_generate": true, "prompt_context": "faulty_product_fos_s75", "export_pdf": true, "escalation_target": "Financial Ombudsman Service", "escalation_url": "https://www.financial-ombudsman.org.uk/consumers/how-to-complain", "escalation_method": "Online form, phone (0800 023 4567), or post"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "small-claims", "order": 18, "title": "Consider the small claims court", "description": "If the retailer continues to refuse and other options are exhausted, you can take them to the small claims court. For claims up to £10,000 in England and Wales, the process is straightforward and designed for individuals without legal representation. Court fees are modest and proportional to the claim amount.", "action_type": "info", "action_config": {"tip": "Small claims court fees: claims up to £300 cost £35, up to £500 cost £50, up to £1,000 cost £70, up to £1,500 cost £80, up to £3,000 cost £115, up to £5,000 cost £205, up to £10,000 cost £455. You can claim these fees back if you win. Most retailers settle once they receive a court claim because defending is more expensive than refunding. You can start a claim online at moneyclaims.service.gov.uk.", "escalation_url": "https://www.gov.uk/make-court-claim-for-money", "letter_before_action": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "letter-before-action"},
  {"step_id": "letter-before-action", "order": 19, "title": "Send a Letter Before Action", "description": "Before starting court proceedings, you must send a formal 'Letter Before Action' (also called a 'Letter Before Claim'). This gives the retailer a final 14-day deadline to resolve the matter. Courts expect you to have attempted this step, and many retailers settle at this point because they know you are serious.", "action_type": "send_letter", "action_config": {"letter_type": "letter_before_action", "auto_generate": true, "prompt_context": "faulty_product_lba"}, "completion_criteria": {"type": "letter_sent", "letter_type": "letter_before_action"}, "wait_after_days": 14, "wait_message": "This is the retailer's final chance. Many companies settle at this stage to avoid court. If they do not respond within 14 days, you can proceed with a court claim.", "next_step": "assess-lba-response"},
  {"step_id": "assess-lba-response", "order": 20, "title": "Did the retailer respond to the Letter Before Action?", "description": "What happened after your Letter Before Action?", "action_type": "branch", "action_config": {"question": "Outcome?", "options": [{"label": "They refunded or settled", "next_step": "resolved"}, {"label": "No response or refusal — I want to proceed to court", "next_step": "court-claim"}]}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "court-claim"},
  {"step_id": "court-claim", "order": 21, "title": "Start your court claim", "description": "You can now submit a claim through the Money Claims Online service. Your TheyPromised case file, timeline, and correspondence form the evidence for your claim. Export your case PDF and keep all letters and responses available.", "action_type": "escalate", "action_config": {"export_pdf": true, "escalation_target": "Small Claims Court (County Court)", "escalation_url": "https://www.gov.uk/make-court-claim-for-money", "escalation_method": "Online at moneyclaims.service.gov.uk"}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": "resolved"},
  {"step_id": "resolved", "order": 99, "title": "Case resolved", "description": "Well done for standing up for your consumer rights. Record your outcome to help others know what to expect from {company_name}.", "action_type": "resolve", "action_config": {"trigger_outcome_form": true}, "completion_criteria": {"type": "manual"}, "wait_after_days": 0, "next_step": null}
]
$steps$::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  sector = EXCLUDED.sector,
  steps = EXCLUDED.steps,
  is_active = EXCLUDED.is_active;
